### ISSUE TITLE
the request either contained a nonexistent path or could not be handled by a single backend: 

### ISSUE THREAD

**Issue by wdhutton** [quasar-analytics/quasar#1100]
I have a config file as : 

{
  "server": {
    "port": 5555
  },

  "mountings": {
    "/": {
      "mongodb": {
        "connectionUri": "mongodb://weedat02.com:27017,weedat03.com:27017,weedat04.com:27017/"
      }
    }
  }
}

start up REPL with 

java -jar core/target/scala-2.11/core_2.11-4.0.3-one-jar.jar -c /root/quasar/quasar/quasar-config.json

then issue "ls"  and see no databases.
cd wdhdb & then "select * from prices" and get

 Quasar error: the request either contained a nonexistent path or could not be handled by a single backend: (select * from `./wdhdb/prices`)

from mongo, I can see several databases including the quasar-test database from tests
sbt test runs to completion w/o errors.

**Comment by wdhutton** [comment]
FYI
Mongo 3.2.0
3 non replicated shards - mongos @ 27017
using wiredtiger engine

**Comment by jdegoes** [comment]
I assume your real configuration has username / password and such?

**Comment by wdhutton** [comment]
nope - wide open test cluster - no user/pwd validation
all the test ran ok - i can see the database and collections that were created.

**Comment by jdegoes** [comment]
OK, well I can tell you this problem is always caused by a malformed config. Quasar ignores the invalid config and loads the default config, which points to nothing. That said, I can't tell you what, if anything, is wrong with the config. It looks like the [example config](https://github.com/quasar-analytics/quasar/blob/master/example-quasar-config.json) which we run through all the tests.

Have you tried with just one server? Also, the version of Quasar you're using is a bit old, I think on the latest you'll actually get an error on invalid config.

**Comment by jdegoes** [comment]
@beckyconning suggests that you may have to specify a database on the path, e.g.: `/foo` at the end of your connection string, where `foo` is a database.

**Comment by wdhutton** [comment]
I reinstalled with latest version and indeed got error messages :

Caused by: java.lang.RuntimeException: Configuration file not found: ./-c

I removed the "-c" from the command line and can now see my database/collections.
thanks for your help.

bad :
java -jar core/target/scala-2.11/core_2.11-4.0.3-one-jar.jar -c /root/quasar/quasar/quasar-config.json

good:
java -jar core/target/scala-2.11/core_2.11-4.0.3-one-jar.jar /root/quasar/quasar/quasar-config.json
