### ISSUE TITLE
Quasar compiles, but tests are failing (NoClassDefFoundError) 

### ISSUE THREAD

**Issue by notz** [quasar-analytics/quasar#1144]
[error] NoClassDefFoundError: : quasar/SKI$class$lambda$$?$1 (package.scala:334)
[error] quasar.SKI$class.?(package.scala:334)
[error] quasar.fp.package$.?(package.scala:344)

Seems that their are missing dependencies from an closed source component (quasar,SKI).

On my devel machine this is working (also 15.10).

**Comment by sellout** [comment]
There aren’t any closed-src components involved in Quasar. The `SKI` object is defined in “quasar/fp/package.scala”. I’ve seen errors like this when sbt gets confused. Have you tried `sbt clean` before building? (The Scala equivalent of turning the computer off and on 🙃)

**Comment by notz** [comment]
Sorry, no expirience in scala. 

After ./sbt clean their is still the same problem.

**Comment by mossprescott** [comment]
@notz: just a wild guess, but what platform are you running SBT on? Those classes have greek letters for names, and I can imagine Windows might get confused.

**Comment by mossprescott** [comment]
Nevermind, I see from Gitter that you're on Ubuntu 15.10.

**Comment by sellout** [comment]
@notz: Just to recap … You have two Ubuntu 15.10 boxes. Your own dev box compiles/runs Quasar just fine, but there’s a server that 1. hangs when you try to run a pre-built version, and 2. fails to build locally with the error above.

It seems like the problem must be some difference in configuration or whatever between the server and your own machine. Where is the server? Your own data center, AWS, etc. That might offer some hint. But I’m not sure this is something we can be much help with, since you have a machine with roughly the same config where it works. The first step is probably figuring out how they differ.

**Comment by notz** [comment]
@sellout yes, you are correct. I have tried it now on all my instances. It seems it works on boxes with more ram (2G vs. 1G) regardless if i define Xmx 

Packages are nearly the same on the 2G boxes the have additional nfs-common package

**Comment by notz** [comment]
@sellout ok, verified that it is the a low memory problem. upgraded the instance to 2G and it is working.

Any reason why quasar needs at least 2G ram, regardless what is defined as Xmx?
