### ISSUE TITLE
Expected type FlexArr(0,None,Top) but found Obj(Map(),Some(Top))

### ISSUE THREAD

**Issue by cvogt** [quasar-analytics/quasar#1213]
When I try to run this query
```
SELECT s[0] from (SELECT asdf.asdf from `/asdf/asdf/asdf` LIMIT 1) as s
```
I get this error message
```
Expected type FlexArr(0,None,Top) but found Obj(Map(),Some(Top))
```

I just started playing with slamdata, so it is quite possible I am trying something unsupported, but the error message doesn't look ideal even then. Looks like there were some toString'ed Scala objects in there. And definitely not something that would tell me "hej not supported"

**Comment by jdegoes** [comment]
This is a known issue due to the consistency of SQL<sup>2</sup>, but what you are trying to do is possible with a slight workaround.

Currently, you have to run this query as follows:

```
SELECT s[0] from (SELECT asdf.asdf from `/asdf/asdf/asdf` LIMIT 1){*} as s
```

Note the added `{*}` at the end, which expands the values from the Javascript objects created by the select query (which all have the form `{"asdf": ...}`).

There is an [open ticket](https://slamdata.atlassian.net/browse/SD-1750?jql=text%20~%20%22single%22) which would allow you to use ordinary SQL syntax for this (ping @sellout).
