### ISSUE TITLE
CI: don't build docs and jars after running coverage

### ISSUE THREAD

**Issue by paulp** [quasar-analytics/quasar#1400]
It looks like we're still doing this on travis job 1:
- build everything with code coverage instrumentation
- run all the tests
- now delete everything
- build it all again without instrumentation
- publish jar/docs

Meanwhile in all the other jobs we're doing this:
- build everything without instrumentation
- delete it without publishing jar or docs

This is adding 15+ minutes to the end-to-end time of each travis run.

**Comment by mossprescott** [comment]
That's correct, except that we actually only publish the jars and docs when we're building `master`.

I would say building the docs is important to do in every build (to make sure we haven't broken scaladoc in PRs). But there's no need to delete the instrumented bytecode before building the docs as far as I know, and there's no need to re-build everything without coverage in any non-master build.

Also, it might make sense to compile and build the "assembly" jar *first*, and then enable coverage. I'm not really sure if that would avoid one of the compiles or not.  For whatever reason, we had trouble with this before, or we didn't want to waste time building jars if the test were going to eventually fail, or something like that.

When the build was faster, it made sense to just run the same steps in every build so we could be confident that they would work when we got to master. Now, maybe not so much.

Also, build #1 is doing much more work because we wanted to have the most complete test before deciding to publish the jars. For example, we used to fail the build if coverage was below 80%. If coverage is important to us at all, there's no getting around running all of the tests in a build with coverage enabled, and that build will always be the slowest by a wide margin.

At this point, I think we could break the builds up this way:

- 1: build and run all tests and the docs, and publish the jars if on `master`
- 2: build and run all tests with coverage enabled
- 3-5: run backend-specific tests

I suspect that this 1 and 2 would finish significantly faster than the current .1, but we'd have to try it to be confident.

**Comment by paulp** [comment]
> That's correct, except that we actually only publish the jars and docs when we're building master.

Okay, I only intended this ticket in the context of master. What we do on PRs is also a question.

> Also, it might make sense to compile and build the "assembly" jar first, and then enable coverage. I'm not really sure if that would avoid one of the compiles or not. 

Nope, that just swaps the order. The instrumented code is completely different: there's no way to enable coverage which doesn't entail rebuilding everything. (There COULD be, given a different architecture - profilers for instance do it with an agent - but it's not how scoverage works.)

> If coverage is important to us at all, there's no getting around running all of the tests in a build with coverage enabled, and that build will always be the slowest by a wide margin.

Right: which is why the thrust of this ticket is the suggestion that the slowest build by a wide margin not also be sequentially tasked with rebuilding the entire project from scratch - that being identical work to that which has already been completed in all the other jobs.

I already divided the work up as described when I had more time to work on this. It finishes a lot faster, as you'd imagine.

**Comment by nicflores** [comment]
I'm experimenting with removing `coverage` from the first build job and moving it to the fifth matrix travis build, `mongodb_3_0`. In addition I'll be moving documentation generation to the sixth matrix travis build, `mongodb_read_only`.

**Comment by sellout** [comment]
I don’t think you can move doc generation, because it needs to be included in the published jars.

**Comment by sellout** [comment]
Also, why not just use jobs 1 & 2?

**Comment by nicflores** [comment]
Thanks for the heads up about the doc generation, @sellout. I've moved it back. Matrix build 2 is Marklogic which take longer than the Mongo builds. The next Mongo build is job 5.

**Comment by nicflores** [comment]
PR #2067 merged.
