### ISSUE TITLE
Cannot create a mount if views already exist

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#1448]
See slamdata/slamdata#989 (closed in favor of this issue).

The sequence seems to be:

1. a mount exists at a certain path, say `/foo/`
1. a workspace is created, perhaps just by exploring within `/foo/`
1. _views get created within `/foo/` by the UI_
1. the mount at `/foo/` is deleted
1. _views are not deleted automatically, and the API reports a *directory* as present at `/foo/`_

Note: at this point, the API _will_ allow a mount to be created at `/foo/`, which is counterintuitive since it also reports that there is already a directory at that path. However SlamData will not allow a new mount to be created at an existing path, so it cannot be done through the UI.

The proposed solution is:

1. delete all nested views when a mount is deleted
1. perhaps also prevent the addition of views outside mounts (see @wemrysi's comment on the slamdata issue)
1. move nested views when the ancestor mount is moved to a new location in the filesystem

**Comment by mossprescott** [comment]
_Updated description above to reflect the result of local testing._

**Comment by beckyconning** [comment]
This also causes errors in decks in filesystems which have been "unmounted".

Decks are still accessible via directories due to views still being available.

Deleting this directory and re-mounting is a workaround for this issue.

Performing the same action as deleting the directory at unmount should fix this issue.
