### ISSUE TITLE
simplify Provenance representation

### ISSUE THREAD

**Issue by sellout** [quasar-analytics/quasar#1550]
Provenance is reified into QScript to be used by bucketed operations, autojoin, etc.

The current representation is verbose and includes unnecessary components. We need a new representation that separates the parts that we need during QScript compilation (for correctly generating autojoins) and the parts that need to be reified for bucketing.

**Comment by alissapajer** [comment]
@sellout wondering if this ticket could be broken into multiple tickets. 

This ticket was partially completed with the merging of #1592, which reifies only the provenance information that is needed past the compile phase.

So I'm thinking, perhaps it makes sense to close this ticket since #1592 is merged, and then add new tickets giving the details of the remaining provenance simplification work? Since only the reification work was initially described here, we could use descriptions of the remaining work.

**Comment by alissapajer** [comment]
@sellout after this release is out, could you describe the remaining work in this ticket? I'm not sure exactly what further work you have in mind to be completed.
