### ISSUE TITLE
Treat single column, unaliased selection expressions as SELECT VALUE

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1711]
When a single projection expression appears in the SELECT clause, and that expression is not aliased, we should treat it equivalent to a SELECT VALUE, and not build a singleton object with "0" and the expression. This just confuses the frontend and it's not necessary in a system that can return sets of raw values (without any decoration in an object or array).

**Comment by sellout** [comment]
So, I agree with this in principle. I’ve made the changes and my one concern is with Mongo’s inability to return non-Map results. So, until the fallback evaluator is in place, Mongo is going to be returning `{ "value": <result> }` instead of just `<result>`. And that at least makes regression tests a bit more of a pain.

So, if anyone has a solution … it’d be helpful.

**Comment by jdegoes** [comment]
@sellout Sounds like you solved this for now (magical unwrap 😄 ).
