### ISSUE TITLE
limit not working, always return 11 result

### ISSUE THREAD

**Issue by Bitomancer** [quasar-analytics/quasar#1806]
limit not working, always return 11 result

**Comment by sellout** [comment]
It sounds like you’re using the REPL. If you were to try `limit 5`, it should work. However, if you specify >10, you’ll always get 10 results, because that is the default value of `summaryCount`. If you set that to a higher number, you’ll get more results. You can run `help` at the REPL to see the vars/commands that are available (although I think the descriptions are lacking).

It _might_ be a good idea to only apply `summaryCount` when a query doesn’t have an explicit `limit`, or alternately, to warn when two adjacent `limit`s are provided (since the larger will be ineffectual).

**Comment by zeeiyerWork** [comment]
Will try and reproduce and close this if I am unable to reproduce.

**Comment by alissapajer** [comment]
`summaryCount` is currently working correctly in the REPL so I am closing this issue.
