### ISSUE TITLE
Support expanded variable name syntax

### ISSUE THREAD

**Issue by natefaubion** [quasar-analytics/quasar#1837]
In the frontend we need to be able to naturally namespace variables, and extending the allowed set of variable name characters is probably the most conservative change. Since variables are already prefixed by `:`, could we allow any series of non-whitespace characters as a variable. That, or ```:`foo.bar baz` ``` like syntax.

```
:foo.bar.baz
:foo:bar:baz
:foo/bar/baz
:`foo bar baz`
```

Would these all not be unambiguous from a SQL^2 grammar standpoint?

**Comment by jdegoes** [comment]
The only unambiguous one is:

```
:`foo bar baz`
```

Because the others have multiple interpretations. This should probably be supported anyway so we can have variable names with spaces or other non-identifier characters.

Another alternative to "name nesting" is more "variable nesting", which would interpret `:foo` as a top-level variable, in which is contained another variable called `bar`, etc. This might be a bit more compositional but is probably not required to implement any of the features that SlamData wants.

If you agree, let's restrict the scope of this ticket to supporting back tic'd identifiers for variable names, as well as any API updates (I don't think there will be any).

**Comment by sellout** [comment]
Yeah, the backtick option looks like a simple change (hahaha) – just need to replace `identifierString` with `ident` in `variParser`. I don’t think it would conflict with any other productions in the grammar.

**Comment by jdegoes** [comment]
@alissapajer Can you pull this to the head of the queue? Should just take an hour or so.

**Comment by alissapajer** [comment]
@jdegoes was just in the middle of a discussion with @sellout about qscript joins - he offered to grab this ticket and do it now so I can keep working on joins

**Comment by jdegoes** [comment]
@alissapajer 👍
