### ISSUE TITLE
Writes view mount config that can't be read back

### ISSUE THREAD

**Issue by natefaubion** [quasar-analytics/quasar#1845]
I started up with a clean `config.json` and ran a workspace (which creates view mounts). When I restarted, the config could not be parsed.

```
Error in configuration file, using default configuration: Failed to parse ./tmp/quasar/config.json: operator ')' expected; `.': CursorHistory(List(El(CursorOpDownField(connectionUri),true), El(CursorOpDownField(view),true), El(CursorOpDownField(/srv/Untitled Workspace 3.slam/.tmp/outdbce9980-7d77-47e3-b6a1-4e508fab8115),true), El(CursorOpDownField(mountings),true)))
```

Which appears to point to this entry in the config:

```
    "/srv/Untitled Workspace 3.slam/.tmp/outdbce9980-7d77-47e3-b6a1-4e508fab8115": {
      "view": {
        "connectionUri": "sql2:///?var.A.results=%60/srv/Untitled%20Workspace%203.slam/.tmp/outeab1f5d1-923c-4012-a170-8340588da3dc%60&q=%28select%20%2A%20from%20%3AA.results%29&var.Foo=%22Baz%22&var.results=%28%60/srv/Untitled%20Workspace%203.slam/.tmp/outf31cb03c-bd15-4e49-8dda-e0f008d27c14%60%2C%60/srv/Untitled%20Workspace%203.slam/.tmp/out2e81bff8-3f5d-44f5-a1eb-6340454a713f%60%29&var.Name=%22Adam%22&var.A.Car=%22Camaro%22"
      }
    },
```

May be related to the liberal variable names.

**Comment by wemrysi** [comment]
@natefaubion Looks like the issue is with the query, `%28select%20%2A%20from%20%3AA.results%29` which, when decoded is `(select * from :A.results)` and doesn't include backticks around the variable name.

You don't happen to have an example of the view creation request made to quasar, do you? If the backticks were present in the original request, then they were lost during serialization somehow, if they weren't in the original request, that should have been an error, I'll try to replicate w/out SlamData.

**Comment by wemrysi** [comment]
I've managed to reproduce this, it looks like the backticks are being lost during serialization.
