### ISSUE TITLE
Option to Treat a MarkLogic File as a Quasar File

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#1847]
We currently assume that a MarkLogic File is the equivalent of a single document or single row in a different database.  @wemrysi and I ran into a use case where a MarkLogic File was actually a collection of many rows / documents.

This resulted in unexpected behavior when querying the Quasar File (which I believe is currently equivalent to a MarkLogic Directory)

For instance, we might expect the `/Users` directory in MarkLogic (which is presented as a Quasar File) to contain 100 MarkLogic files, perhaps labeled `User1.xml`, `User2.xml` and so on.  So performing a `SELECT * FROM Users` might return multiple entries, one per user.

Instead, if that same MarkLogic directory contained a single MarkLogic File named `Users.xml` which stored multiple users, when we perform a `SELECT *` on that file, rather than getting one entry per user, we get a single entry with an array containing all the users.  @wemrysi keep me honest here, please.

This is a request to enhance the MarkLogic connector to allow for this situation

**Comment by wemrysi** [comment]
@damonLL @jdegoes I am currently thinking of approaching this by leveraging the support for querying over arbitrary paths that @sellout has worked on. This would mean that specifying a directory path in a query results in an input dataset comprised of the root documents of all the descendant files in the directory. Specifying a file path would result in an input dataset comprised of the children of the root document in the file (or maybe just the root document itself and then left shift?).

We could also choose to have directory queries only include their immediate child files (instead of all descendants), I'm not sure which is preferable. There doesn't seem to be a way to allow the user to choose at query time (yet?), though maybe @jdegoes or @sellout has an idea? It could also be a configuration option to the mount, which should be fairly useful given the granular mounts enabled by #1854.

This has implications for ingesting data as well. As @damonLL pointed out, a Quasar file is currently modeled as a physical directory with each line in the Quasar file represented as a single physical file in the directory. I think we'd want to drop this encoding in favor of a direct mapping of quasar directories and files to physical directories and files. Thus uploading a file to quasar will result in a single file in MarkLogic.

How does this sound?

**Comment by jdegoes** [comment]
1. Makes sense.
2. I think it should only include immediate child files. @sellout?
3. Yes, this is beneficial for users.

**Comment by sellout** [comment]
I don’t think that “directory queries only include their immediate child files” really makes sense in the MRA model (which makes no distinction between a map and a directory of files).

Also, it sounds like ML actually supports both files that have only a single value in them as well as files that contain multiple values. Are these actually different file types in some way, or is it the case (as with most stores) that the single-value files are simply the same as multi-value files with just a single entry in them? This makes a difference in the way we can present them from QScript (separating the `ExpandDirs` transformation is one of those).

**Comment by wemrysi** [comment]
@jdegoes 2. That would match the current behavior, I was just wondering how intuitive it was. However, I think I agree it is the way to go as otherwise there isn't a way to just query the children of a directory high up in the hierarchy. Whereas if queries only return children one can always union multiple subdirectory queries to achieve the "descendants" behavior, albeit at the cost of more explicit enumeration.

@sellout It supports well-formed XML and JSON (among other) files both of which result in a single root value. It appears to be common practice to store sets of data in a single file, think `<Customers><Customer>...</Customer><Customer>...</Customer></Customers>` or a JSON array. Would it be more consistent to just return those single values and require the user to left shift them in the query if they want the children?

**Comment by jdegoes** [comment]
> I don’t think that “directory queries only include their immediate child files” really makes sense in the MRA model (which makes no distinction between a map and a directory of files).

I thought @wemrysi was referring to "immediate children" (e.g. `{*}` or `[_]`) versus transitive children (for which MRA has no operator but it's possible with missing fracture / unfracture & pattern matching).

**Comment by sellout** [comment]
So, I’m still very confused about the first part … or rather, there’s an important distinction between user queries and ML queries, and we have to figure out how to align those things via QScript, etc. So it might be a discussion for a Slack Call or something.

The second part makes it sound like, yes, ML should be using `Read`, not `ShiftedRead` … but that doesn’t really matter to user queries much. E.g., the query `select * from zips` is going to be something like `LeftShift(Read("/zips"))` or `ShiftedRead("/zips")`, they both have the same semantics, it’s just a matter of which maps better to the particular data store.

@jdegoes No, I’m _pretty_ sure he means that if you do `select * from foo`, where `foo` is a directory, what does the result look like. It has to include all of the directory (and file) names as keys in a map, with directories containing maps of children, etc.

@wemrysi “specifying a directory path in a query results in an input dataset comprised of the root documents of all the descendant files in the directory.” So, when you switch to `Read`, specifying a directory path in a query results in a _value_ which is a Map containing the names of the immediate child dirs & files as the keys, and the contents of those as the entries, recursively.

But, @rabbitonweb started working on an analysis to provide the set of fields required from the `Read`, so if `select foo, bar from baz` is querying a directory `baz`, and `foo` and `bar` are simply files in that directory, then you can still avoid the extra work in the query, because you know you don’t have to care about any more deeply nested dirs. And if `bar` happens to be a dir, then you know you only have to care about that one dir. But with `select * from baz`, you _will_ need to aggregate _all_ of the subdirs.

**Comment by wemrysi** [comment]
@sellout @jdegoes As an incremental step to supporting all of MRA while enabling the use-case outlined in this issue, what if directory queries resulted in a map with immediate child file names as keys and their contents as values, ignoring sub directories?

This seems forward-compatible with full MRA support (as sub directories will just begin appearing as map keys once supported).

**Comment by wemrysi** [comment]
@jdegoes Ran into another hiccup with this during some testing with SlamData today that may have implications on its release.

We currently return the set of physical inputs to a query in the response from the `/compile` endpoint (#1224), but we do so in a way that assumes all the paths in `LogicalPlan` map directly to physical files. This had been true up until now, but paths can be a file or a directory in MarkLogic (and could eventually be deeper than a file if one is addressing some substructure of data), so this no longer works and it looks like we'll need to ask the connectors themselves for the set of physical inputs.

This affects SlamData's use of this information as, until it is fixed, paths that reference physical directories will be returned as files, not directories, causing operations like permissions granting and metadata checks to be incorrect or fail with a "resource not found".

Filesystem operations and queries on directories themselves will still work in MarkLogic, however it doesn't look like directory queries will work from within SlamData until the correct paths are returned.

**Comment by jdegoes** [comment]
@wemrysi I think this is worth fixing after this ticket. I bumped it to 4.2.
