### ISSUE TITLE
Select value with order by results in empty objects

### ISSUE THREAD

**Issue by natefaubion** [quasar-analytics/quasar#1856]
```
SELECT DISTINCT(state) FROM :results ORDER BY state
```

Results in a list of empty objects, instead of `{ value: foo }` objects. Removing the ORDER BY yields correct results.

**Comment by sellout** [comment]
Ok, this is a pretty specific interaction of `select distinct` on a single field when you `order by` just that same field. Which I’m guessing is actually a pretty common case when you’re, say, trying to populate a list of values.

Like, even `select distinct null, state from :results order by state` works just fine.

My suspicion is that this behavior was introduced by #1799. It should only affect MongoDB (because the bug is in the crazy way we try to identify a `sort` that happened before the `distinct` and duplicate it after the `distinct` – yay for SQL semantics).

**Comment by sellout** [comment]
Actually, the behavior where we repeat the sort after `sort; distinct` should be implemented in the SQL->LP compiler. We shouldn’t be assuming in LP or QS that distinct with a sort before it is still ordered.

**Comment by jdegoes** [comment]
@sellout Looks like this is a 4.1 blocker. Let's discuss when you're online.

**Comment by sellout** [comment]
This is actually what I am in the middle of right now. Although, my current approach fixes a more general problem with `distinct` in all connectors. I’ll take a look right now to see if there is a quick fix to this specific case in old Mongo.

**Comment by sellout** [comment]
Oh, I thought of a possible workaround – let me know if it’s easy for you to implement. The benefit of this is that it’ll also give you consistent results across backends (all like `{ "value": foo }`, whereas the real Quasar fix at the moment would have results like `{ "value": foo }` on MongoDB and `foo` on other connectors.
```sql
SELECT DISTINCT state AS value FROM :results ORDER BY value
```
The `AS` is the important bit. It means that we end up returning a document rather than the ordered-by value, which _should_ avoid the bug you’re hitting.

**Comment by natefaubion** [comment]
The problem is I can't make this substitution in general, and this is affecting user-written queries.

**Comment by jdegoes** [comment]
@sellout Shouldn't this query be:

```sql
SELECT DISTINCT(state) FROM :results ORDER BY DISTINCT(state)
```

which selects the distinct field and orders by the distinct values.

Or, alternatively and equivalently:

```sql
SELECT DISTINCT state FROM :results ORDER BY state
```

The latter being the `DISTINCT` variant of `SELECT` which applies a distincting operation to the results of the selection, preserving order.

**Comment by sellout** [comment]
@jdegoes Yeah, I think that’s right – however I think the function form of `distinct` is currently behaving the same as `select distinct` in this case – perhaps a bug in the parser, since the select has only a single projection, that the `()` is read as precedence rather than function arguments. That’s just a guess, though. The SQL²->LP compiler certainly handles `select distinct(state)` differently than `select distinct state` if the former were actually parsed to the correct AST.
