### ISSUE TITLE
Enhance /compile endpoint to provide additional details

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1941]
SlamData would like additional information on queries, including:

 * Provide names and types of variables used in queries.
 * Provide list of imported modules, and list of functions in such modules which are called (#1792).

This structured information will help allow SlamData to make robust dependency determination.

**Comment by garyb** [comment]
Yep, this covers it perfectly as far as I'm concerned! @beckyconning?

**Comment by beckyconning** [comment]
Yep this looks good to me! Should I remove #1939?

**Comment by jdegoes** [comment]
@beckyconning Sorry, I didn't see that one. 😦 Yes, we can close that one or this one, whichever.

**Comment by beckyconning** [comment]
As we need to know what variables are required by a query (i.e. written by a deck author) we can not use only processes so without this feature we can not introduce processes into the front end. Currently no-one is assigned to this issue so shall we move https://github.com/slamdata/slamdata/issues/1474 and https://github.com/slamdata/slamdata/issues/997 to April?

**Comment by beckyconning** [comment]
@jedesah @garyb

**Comment by jedesah** [comment]
@zeeiyerWork Happy to work on this once I am done with the next two subtasks on #1792. I can do this before the third subtask (imports) since they are not required by the front-end for this upcoming release.

**Comment by jedesah** [comment]
@beckyconning @garyb I'm wondering whether what you guys need should be part of this endpoint or if it's another endpoint. This endpoint is designed to provide information on a "complete" query. i.e it will error out if you don't supply all variables in the query which kind of defies the point since if I remember correctly what you need is to discover what are the variables referenced in the sql expression?

Then again, this endpoint should probably (maybe it already does) error out if you give it a sql expression with variable references but do not supply all the variables in the uri as query parameters, maybe that error (or a slightly improved version) would be sufficient in order to provide the information you need?

**Comment by jedesah** [comment]
I'm assuming the type information is needed to provide a better UI experience for the user? Perhpas we can hop on a call at some point and discuss and post meeting notes here for posteriority. In the meantime I'll see what kind of error the compile endpoint produces when not all variables are supplied and see if it's sufficient for at least the most basic needs in terms of creating "parameterized views"

**Comment by garyb** [comment]
> This endpoint is designed to provide information on a "complete" query. i.e it will error out if you don't supply all variables in the query which kind of defies the point since if I remember correctly what you need is to discover what are the variables referenced in the sql expression?

Ah, yeah! I think we probably will need a new "analyse" endpoint or something like that, since as you say, a big motivation for this is to find out what variables are going to be needed.

We probably could use the existing form, by just passing in all the variables we have in scope (that's what we currently do when making queries), but I think ideally we wouldn't want to do that.

A call sounds good for sure though. Things are a bit crazy at the moment as we're doing the front-end team meetup at the moment, but will try and sort something out.

**Comment by jedesah** [comment]
@garyb @beckyconning So once #2050 is merged at least the `compile` and `query` endpoints will return ALL variables missing when any variable is missing from the query. I know it's a little odd to use an endpoint purposefully for the failure case in order to extract information from the error message but at least it makes what you need to do possible.

We can discuss next week (or sooner if need be) what a new endpoint might look like to get more information or just more convenient to get the same info.

**Comment by beckyconning** [comment]
Thanks @jedesah !

**Comment by jedesah** [comment]
What was needed for 4.2 was done after discussion on this ticket. However what is discussed in initial ticket description was not done as part of work on 4.2
