### ISSUE TITLE
Experiment with caching */target/

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#1982]
We may be able to aggressively cache `target/` in Travis for PR builds only (cleaning it out on master).  This should, in theory, allow us to have much faster (incremental) PR builds while still maintaining reproducible and trustworthy master builds.

**Comment by djspiewak** [comment]
Done a while ago.  Ticket never got closed.

**Comment by zeeiyerWork** [comment]
Closing this ticket, since this experiment was done and implemented and we have feedback from Quasar developers around feedback from Travis being a "lot more instantaneous" now. Basically, there is now intelligence to detect if PR or Master Build. If PR build, then we cache target directory, If MASTER build, then we go for safety first to hedge against any compiler issues and the possibility of a corrupt artifact.
