### ISSUE TITLE
Improve Build Times, so Application Developer Feedback cycles are shortened.

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#1993]
Many possibilities - see https://docs.google.com/document/d/1DwabbFo-vPfKjMnHT1VmWO-3dkjQEAnaADFIda1z83k/edit

In addition - @djspiewak , @nicflores -> worked on a way to (based on a Travis environment variable) to cache target directory for PR (but not for master), given lack of trust on the correctness of build-artifacts, generated thusly.

**Comment by nicflores** [comment]
This line:

` 21   - ./scripts/installMongo mongodb-linux-x86_64-${!MONGO_LINUX} mongo ${!MONGO_PORT} ${!MONGO_AUTH}`

in the `.travis.yml` file of quasar installs mongodb inside the container in which the tests run. Instead we should use the docker environment provided by Travis to pull mongodb images from docker hub and use them during testing. Using something like:

````
before_script:
  - docker run --name slamdata-mongodb-2-6 -p 27018:27017 -d tutum/mongodb:2.6
  - docker run --name slamdata-mongodb-3-0 -p 27019:27017 -d mongo:3.0
  - docker run --name slamdata-mongodb-3-2 -p 27020:27017 -d mongo:3.2
  - docker run --name slamdata-mongodb-3-4 -p 27021:27017 -d mongo:3.4
````

we can bring up all 4 versions of mongo we need to test on in their own separate docker containers within the Travis docker environment. @djspiewak and I spoke about this yesterday and thought this may be a good way to go especially since spinning up one of these containers takes approximately 10 seconds each.

@drostron pointed out to me yesterday that Couchbase and MarkLogic scripts already run in containers within Travis. If we moved the docker commands in each of those scripts to `before_script` section it would make it more explicit what our testing environment looks like. Any prepping of these databases can be done in a single script that is called once they are all up and running.

Cleaning up the `.travis.yml` file and leveraging the docker environment Travis provides will help pave the way to allowing developers to test locally using docker.

**Comment by nicflores** [comment]
The refactoring of the `.travis.yml` file mentioned above has happen in this [PR](https://github.com/quasar-analytics/quasar/pull/2037). Currently, we are at around a 30min build time on PRs, sometimes a little less depending on the changes and on whether or not Travis is running 15 concurrent builds. At this point with the updated caching by @djspiewak and the containerization of the travis build I believe we are at good point to call this issue done. We can always re-visit the topic of this becomes an issue again.

**Comment by djspiewak** [comment]
👍  We can reopen a more specific issue for future problems.
