### ISSUE TITLE
Workspaces do not reopen from within MarkLogic XML mount

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#2124]
SlamData version 4.1.5
MarkLogic 8.0

Creating a workspace inside of a MarkLogic **XML** mount appears to be broken as you cannot reload it after it's created.  An error is presented when attempting it:

```
Couldn't load this SlamData workspace.
Unexpected result when loading value from file.
```

I've tried very simple workspaces such as Query Card -> Preview Table Card and it fails to reload after I exit the workspace.

Note that I do not see this problem when using a MarkLogic **JSON** mount.

**Comment by jsantos17** [comment]
After some investigation I have discovered that this issue is related to #1642. The document describing a deck uses UUIDs as key values. These documents fail to serialize into XML due to UUIDs not being valid QNames.  The problem is that most often than not the document representing the deck will contain at least one key UUID that start with a number. If I'm understanding correctly the [productions here](https://en.wikipedia.org/wiki/QName), this is not permitted.

So, the root issue is not that decks don't load, but that decks don't save at all due to the UUIDs. This is an example of a document representing a deck. This fails to serialize into MarkLogic.

```
[
  {
    "decks": {
      "4773af9f-50ff-4a45-b88d-9b7f4e367222": {
        "cards": [
          "17a3f09c-059b-4407-8e9f-f494f9d13db1"
        ],
        "name": ""
      }
    },
    "cards": {
      "17a3f09c-059b-4407-8e9f-f494f9d13db1": {
        "model": {
          "ranges": [
            
          ],
          "text": "SELECT \"Hello, World!\""
        },
        "cardType": "ace-sql"
      }
    },
    "rootId": "4773af9f-50ff-4a45-b88d-9b7f4e367222",
    "version": 2
  }
]'
```

We probably want to discuss how to handle this. We can implement a workaround or tackle #1642 and solve this issue along with it. The scope of #1642 appears to be rather large and this problem seems fairly serious to me so I'm inclined to implement a workaround so we can at least save decks when using XML connections.

What do you think @wemrysi? cc @damonLL

**Comment by jsantos17** [comment]
I have confirmed it works fine if replace the UUIDs starting with numbers with UUIDs starting with letters.

**Comment by wemrysi** [comment]
@jsantos17 If we can come up with a workaround that is significantly easier than #1642 in the short-term, then that might be worthwhile, otherwise it probably just makes sense to solve #1642 which will also help on the query side of things.

It also looks like the failure to save the document isn't being communicated properly (see #2197).

**Comment by jsantos17** [comment]
@wemrysi After reading the encoders/decoders/planners in the Marklogic connector I can't think of a workaround that doesn't involve making similar changes to those #1642 would entail. So I believe we should start working on #1642. Seems to me that it'd solve a few of other issues too. 

I will take a look to #2197. The error messages are not very useful indeed.

**Comment by damonLL** [comment]
I see this issue has been closed @wemrysi and @jsantos17 but I'm still seeing this behavior when trying to reopen a workspace from a Marklogic XML mount as seen here: http://d.pr/i/mdT1G1 this is in 4.2.2 master from 6/22/17.

**Comment by jsantos17** [comment]
@damonLL this is odd. I definitely expect this to work. Let me try and reproduce.

**Comment by damonLL** [comment]
@jsantos17 figured this out for me. We have a restriction that doesn't allow you to save a document with the same name in the same location if there is already one there in a different format.

So when executing a query and SlamData attempted to save the workspace on the MarkLogic XML mount, there was already a workspace named `Untitled Workspace` on the MarkLogic JSON mount.

The `500` error that @jsantos17 caught is listed below for clarity's sake:

```
"A document with a different format exists at /Untitled%20Workspace.slam/index
(filesystem:error): on line 10↵---BEGIN QUERY---↵xquery version
"1.0-ml";↵↵declare namespace filesystem =
"http://quasar-analytics.org/filesystem";↵↵declare function
filesystem:file-exists-in-other-format($uri as xs:string) as xs:boolean
{↵  if (fn:doc-available($uri)) then fn:empty(cts:search(fn:doc(),
cts:document-query($uri), ("format-xml"), 1.0, ())) else fn:false()↵};↵↵declare
function filesystem:move-file($srcUri as xs:string, $dstUri as xs:string) as
item()* {↵  if (filesystem:file-exists-in-other-format($dstUri)) then
fn:error(xs:QName("filesystem:error"), fn:concat("A document with a different
format exists at ", $dstUri)) else let $_1 := xdmp:document-insert($dstUri,
cts:search(fn:doc(), cts:document-query($srcUri), ("format-xml"), 1.0, ())), $_2 :=
xdmp:document-delete($srcUri) return
()↵};↵↵filesystem:move-file("/Untitled%20Workspace.slam/temp-1bdc662b-4d8c-44be-9c66-2b4d8cc4bea5",
"/Untitled%20Workspace.slam/index")↵--- END QUERY ---"
```

**Comment by jsantos17** [comment]
@damonLL As part of having a working Marklogic connector, I just thought we might want to improve this error message. I wonder how common it is for customers to have both JSON and XML in the same database. Any input from the use cases of potential customers?
