### ISSUE TITLE
_id field in MongoDB can no longer be queried

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#2141]
Using quasar release 16.0.25, as well as with SlamData 4.2.0 QA prerelease.

Workspaces querying the `_id` field for MongoDB documents now fail with an error message.  A query without the `_id` field:

```
💪 $ select name from tvshow
Query time: 0.0s
 value    |
----------|
 Jack     |
 Kate     |
 Sawyer   |
 Hurley   |
 Juliet   |
 Desmond  |
 John     |
```

with the `_id` field:

```
💪 $ select _id, name from tvshow
Quasar error: keyword 'except' expected; but found `*** error: '!' expected but _ found'
```

This occurs whether or not an alias is provided for the `_id` field.

**Comment by jdegoes** [comment]
@damonLL Just to diagnose, please try:

```sql
select `_id`, name from tvshow
```

**Comment by damonLL** [comment]
Thanks @jdegoes that seems to work, but you still do need to provide an alias, which is acceptable.  Should have tried back ticks.  Not sure if this is expected behavior so I'll leave it open for now, please feel free to close if it's expected, and I'll simply doc it.

```
💪 $ select `_id`, name from tvshow
Query time: 0.0s
 name     |
----------|
 Jack     |
 Kate     |
 Sawyer   |
 Hurley   |
 Juliet   |
 Desmond  |
 John     |
💪 $ select `_id` AS id, name from tvshow
Query time: 0.0s
 name     | id |
----------|----|
 Jack     |  1 |
 Kate     |  2 |
 Sawyer   |  3 |
 Hurley   |  4 |
 Juliet   |  5 |
 Desmond  |  6 |
 John     |  7 |
```

**Comment by sellout** [comment]
Yeah, this was an intentional change. The motivation was ambiguous parsing of various constructs like `[_]`. And SQL doesn’t actually allow unquoted underscores, so it seemed like a reasonable move.

The “id problem” is something we have to solve in general. Right now, getting the id of a record requires knowledge about how that store stores ids. In Mongo, it’s just an extra field named `_id`, but in Couchbase, it’s something like `meta(*).id` (sorry, @drostron, I’m sure I butchered that). There _is_ a generic way to get ids, but it’s onerous, and maybe not actually queryable via SQL² currently. Effectively, something like `select {_:} as key, {:_} as value zips`. (Note the missing `from`, which would trigger the LeftShift (throwing away the id) before we could extract the keys from it).

**Comment by zeeiyerWork** [comment]
Based on chat with @sellout, this behavior is intentional - so closing this out. Docs need to be updated by @damonLL ...
