### ISSUE TITLE
Support download options on `/invoke`

### ISSUE THREAD

**Issue by natefaubion** [quasar-analytics/quasar#2342]
`/invoke` needs to support the same download options as `/data` so consumers can download data sets generated by processes.

**Comment by natefaubion** [comment]
@zeeiyerWork FYI this is a blocker for landing processes in the frontend.

**Comment by jedesah** [comment]
@natefaubion Is this something you've tried out already? Perhaps you haven't because I might have mentioned that I wasn't sure if this would work. However, after having a look at the implementation and writing a new api level test, I believe this should work already. It's proving a little tricky to test this in my browser just for extra certainty on my machine right now due to other things I need to setup in order to do so (I rarely test things manually, which can be good and bad), I'll continue to do so after lunch, but I wanted you to know as soon as possible since you mentioned this was blocking that this might already work as expected. Alternatively, if it turns out that our api tests asserting the presence of the `Content-Disposition` header in the response is not actually translating to the browser downloading the file, that would be good to know, but like I said I'll continue to test this after lunch

**Comment by natefaubion** [comment]
If it supports that as well as the `response-headers` query parameter (which we use to control the filename), then we should be 👌

**Comment by jedesah** [comment]
Already works as expected
