### ISSUE TITLE
Provide optional `QScript` without `MapFuncCore.Guard`

### ISSUE THREAD

**Issue by alissapajer** [quasar-analytics/quasar#2408]
Some backends, like mimir, include typechecking in their internal representation and so don't need `QScript` to provide `Guard`s. Thus it should be possible for a backend to receive `QScript` sans `Guard`.

This is not a blocking issue because the workaround is trivial: when a `Guard` is received, simply pass along the data without checking the type.

It is important that each backend that opts out of `Guard` audits its internal typechecking to ensure it's catching all the cases that `Guard` would.

**Comment by sellout** [comment]
I’m curious exactly what this means. There are a couple things I can think of.
1. if mimir has schemas, it could provide better types to `ShiftedRead` than the `Top` we currently assume (I thought there was an issue for this, but #2387 is the closest I can find).
2. if mimir safely (i.e., evaluates to something we can interpret as undefined) handles incorrectly-typed arguments, then we can delete `Guard`s

Currently Mongo has a hacky approach to (1) that deletes checks that make sure `ShiftedRead` returns a set of String-keyed Maps, but having it truly use that info during typechecking could reduce other type checks as well, especially on more schemaful stores.

For (2), we have to be careful, because it’s possible that different stores have different ideas of what types are allowed. E.g., if a store uses the same operator for addition and string concatenation (and perhaps even auto-converts numbers to strings – I know that’s too crazy, no system would do that, but bear with me here …), then we can’t delete a guard that ensures the arguments to SQL²’s `+` are numbers, because when we try to perform `"foo" + 3`, we’ll get back `"foo3"` instead of the specified undefined.

Mongo’s aggregation pipeline is relatively safe as (2) describes, but I avoided eliminating the guards both because of the issue above, but also because Mongo has some additional complication with a guard perhaps preventing a value from being used in a subsequent `mapReduce`, which wouldn’t be safe.

An additional wrinkle is that `Guard`s aren’t necessarily placed where it’s obvious what they’re guarding. I.e., it doesn’t look like
```scala
Add(Guard(x, Number, x, Undefined), Guard(y, Number, y, Undefined))
```
but rather
```scala
Guard(x, Number, Guard(y, Number, Add(x, y), Undefined), Undefined)
```
And can easily be much farther away from the expression they’re guarding.

**Comment by alissapajer** [comment]
So, I think for now mimir should just throw away `Guard` nodes. This is trivial to do and doesn't require changing `QScript`.

Furthermore, it's possible that some `Guard`s have been directly added by the user, and these we should not throw away. So we will need to detect this situation. 

I'm going to close this issue for now because I don't think anymore that simply omitting `Guard`s is actually the correct solution, given all the nuances.

**Comment by alissapajer** [comment]
@sellout regarding your points:

1. mimir does have a way to represent schemas, but we don't have that pre-computed to provide to a `ShiftedRead`. Unless I'm misremembering (ping @djspiewak). It would be cool if we did that though.
2. This is what I was thinking when I wrote the issue.
