### ISSUE TITLE
Leverage $substr to convert from numbers to strings, and avoid map/reduce

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#2453]
Use this hack -> 
$substr:["$foo", 0, -1 ] will convert a foo number to a string in older versions of MongoDB. This is an undocumented hack.

**Comment by alissapajer** [comment]
@rintcius this issue was fixed by #2591 which has been merged to next-major. But the "fixes", "closes", etc keywords only work when a PR is merged to the repo's default branch, which in our case is master. So this issue didn't close automatically. 

We can close it manually now. Or alternatively we could add the "fixed in new mongo" label, but if we did that we'd have to later again verify that this is fixed. I'm comfortable calling this fixed now, and thus closing this issue now. What do you think?

**Comment by rintcius** [comment]
@alissapajer I discussed this briefly with @zeeiyerWork yesterday and we agreed to keep them open with "fixed in new mongo", even for low-risk issues like this.

**Comment by rintcius** [comment]
verified
