### ISSUE TITLE
Confusing error message when parsing multi table join in Mimir

### ISSUE THREAD

**Issue by dugdun** [quasar-analytics/quasar#2639]
Quasar 20.14.3

When trying to test a multi table join in Mimir I got a warning about not being able to evaluate cartesian sets.

This SQL was entered into a **Query Card**.

```
select distinct
        f.DEST.CODE as DestCode
    ,   a.Description as DestAirport
    ,   f.ORIGIN.CODE as OrigCode
    ,   d.Description as OrigAirport
    ,   f.AIRLINE.UNIQUE_CARRIER as CarrierCode
    ,   c.Description as CarrierDesc
from
        `/mimir/test/flights-short.csv` as f
inner join
        `/mimir/test/airport.csv` as a
    on
        f.DEST.CODE = a.Code
inner join
        `/mimir/test/airport.csv` as d
    on
        f.ORIGIN.CODE = d.Code
inner join
        `/mimir/test/unique_carriers.csv` as c
    on
        f.AIRLINE.UNIQUE_CARRIER = c.Code
```

When I clicked on the **Run Query** button, I got the following error.

```
An error occurred during query compilation.

Physical filesystem error.

cannot evaluate cartesian of sets with size ExactSize(6435) and EstimateSize(6435,32175000)

Quasar error details
{
  "error": {
    "status": "Physical filesystem error.",
    "detail": {
      "message": "cannot evaluate cartesian of sets with size ExactSize(6435) and EstimateSize(6435,32175000)"
    }
  }
}
```

It is not know what is meant by the values of `6435` and `6435,32175000` in the above error.

Note that this same query runs to completion in MongoDB on the same data set without any indexes on the tables in just a few seconds.

**Comment by djspiewak** [comment]
For posterity, the values in the error represent table sizes.  The former represents a size which is known to be *exactly* 6435 rows, while the latter represents an uncertainty range, lower-inclusive and upper-exclusive.  Thus the latter means that the table in question could have as few as 6435 rows and as many as 32,175,000.  The cartesian failed because 6435 * 32175000 = 207,078,300,000, which is a *lot* of rows.

The exception comes out of the fact that Precog was a multi-tenant hosted solution, and we didn't want people accidentally (or deliberately) DoSing us by running queries which could not feasibly complete within weeks, years or even millennia (which was comparatively easier to accidentally do in Quirrel than it is in SQL^2).  As we are no longer a hosted platform, it's a little harder to justify this check, since the only hard resources a user would be chewing through with such a query is their own.  Furthermore, we have plans for a significantly more granular query analysis tool down the line which will allow us to communicate to users how and why their query might be bad, and give them a more reasoned choice about whether or not to run it anyway (as opposed to just forcibly refusing to run the query).
