### ISSUE TITLE
Fix workspace download issues when views/module mounts are referenced.

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#2741]
- Metadata to decorate views/module mounts.
- Serialize referenced views/modules when downloading/exporting workspaces, such that deserializing it "just works". One may have to think through relative imports as well, when it comes to mobility of workspaces across VFS locations.

See https://github.com/slamdata/slamdata/issues/2144 for more conversation.

**Comment by jedesah** [comment]
So here is my proposition for a solution to this issue which assumes "import/export" of a workspace is still useful/necessary now that `COPY` is supported natively in the filesystem. I believe it is since @dugdun and @damonLL want a way to be able to import a workspace of a client and play around with it.

First off, I modified the `data` endpoint to return a description of a function when the path points towards a function file instead of returning an error message. I guess I can do the same thing if the path only points to a module directory.

As for the main objective of this issue, that is, what happens when you download a directory, my plan is for the zipped directory that we serve the client to have the following structure:

Let's say some directory in Quasar contains a normal file, a view and a module directory. Then the zip archive will contain the following:

normalFile -> contents of normal file
viewFile   ->   contents (at the time of the request) of the evaluation of the query in the view file
viewFile.mount -> json representation of the view (i.e sql query)
moduleFile.mount -> json representation of the module

That way, when we upload a zip archive, we can look for these "mount" files in order to restore a filesystem directory to the exact structure of the directory that we "exported"

Notice, there is no moduleFile since that's non-sensical since we wouldn't know which arguments to use to call any function in the module.

I'll need to look into this more tmr, but I think the current behavior is the above minus the `.mount` file entries.

I've already started working on this, so hopefully should have a PR tmr. Just wanted to jot down my design that just crystallized in my head to make sure I understand the requirements properly so that this solves the problem that needs to be solved.

**Comment by zeeiyerWork** [comment]
@jedesah:
>> import/export" of a workspace is still useful/necessary
Yes as discussed earlier, this is how we move workspaces across Slamdata Installs (like an "export" - e.g. when filing a support ticket from customer install to SD-engineer install).

Yeah seems like getting the definition of the module, view + data will suffice. In case of actually copying the contents of the view, I suppose it may not scale as a function of view-data-size (so perhaps a warning or an option in the future based on the size of the view). 

But for now, time-to-market is important - end-users should be able to download workspaces that reference both views and modules - so the fastest path to that is desirable and it seems like your proposal provides for that.

**Comment by damonLL** [comment]
More importantly, this use case is really valuable moving workspaces into Production for customers, not necessarily for our benefit. They need a way to properly promote between environments. Right now we ask them to backup the database and restore it, not a good answer.

**Comment by jedesah** [comment]
Something that I realized during a call with @beckyconning regarding https://github.com/slamdata/slamdata-backend/issues/239 is that I'll want to add a flag to turn on or off downloading of the `.mounts` files as downloading them all the time would mean that the data endpoint would always make use of the `Mounting` algebra (even if there were no mounts in the directory) which means that applications such as SlamData Backend which do things such as authorization would require read permissions on mounts as well as on data in order to download anything which seems less than ideal (although apparently the data endpoint already requires mount permission for a reason I don't fully understand). If there is a way to turn this functionality off though, this seems like less of a problem.

**Comment by jedesah** [comment]
As discussed in frontend meeting this morning, phase 1 (just ignore modules): https://github.com/quasar-analytics/quasar/pull/3160

**Comment by jedesah** [comment]
I will say that #3160 fixes this and we can open a new issue if we want import/export endpoints which would allow workspaces to work after "importing" without opening edit mode first. But my understanding is that this is not required for 5.0

**Comment by zeeiyerWork** [comment]
correct. At some point though soon (e.g. 5.1.0), we do need to fix the "having to open workspaces in edit mode" after upgrade problem - since its a major irritant as per field's feedback.
