### ISSUE TITLE
Missing typechecks for results of `Divide`

### ISSUE THREAD

**Issue by jsantos17** [quasar-analytics/quasar#2755]
Whenever we perform a `Division` with an unknown type and a known integer, the typer assumes the result of the division will always be an integer and guards are not inserted before the result is used an integer.

Consider:
```sql
select substring("abcdefg", 0, pop / 10000) from zips
```
yields the logical plan

```
Typechecked:
Invoke(Squash)
╰─ Let('__checku0)
   ├─ Read(/zips)
   ╰─ Typecheck(Obj(Map[], Some(Top)))
      ├─ Free('__checku0)
      ├─ Let('__checku1)
      │  ├─ ObjectProject(Free('__checku0){"pop"})
      │  ╰─ Typecheck(Int)
      │     ├─ Free('__checku1)
      │     ├─ Invoke(Substring)
      │     │  ├─ Str("abcdefg")
      │     │  ├─ Constant(Int(0))
      │     │  ╰─ Invoke(Divide)
      │     │     ├─ Free('__checku1)
      │     │     ╰─ Constant(Int(10000))
      │     ╰─ Constant(NA)
      ╰─ Constant(NA)
```

Note `Invoke(Substring)` is invoked with the unguarded result of the division, even when we don't know the result will be an integer or a decimal/floating point

```
      │     ├─ Invoke(Substring)
      │     │  ├─ Str("abcdefg")
      │     │  ├─ Constant(Int(0))
      │     │  ╰─ Invoke(Divide)
      │     │     ├─ Free('__checku1)
      │     │     ╰─ Constant(Int(10000))
```

The typechecker works properly with literals in the query:

```
select substring("abcdefg", 0, 10 / 10000) from zips
```

results in 

```
Quasar error: [You provided a constant value Dec(0.001) where we expected a Int...]
``` 

(ellipsis mine)

This is affecting Mongo since version 3.4. 3.4 introduced `$substrCP` and deprecated `$substr`. The latter would automatically truncate a decimal before performing obtaining the substring. `$substrCP` is not as tolerant and simply throws an error.

This isn't blocking new Mongo since there's a principled workaround for queries that no longer work due to a lack of magical truncation:

```sql
select substring("abcdefg", 0, trunc(pop / 10000)) from zips
```

Branched off #2667.

**Comment by edmundnoble** [comment]
Here seems to be the issue, after talking about it with @alissapajer.

Exhibit A:
https://github.com/quasar-analytics/quasar/blob/aeab8f8e92362699aeb3715dba32e0200f39c7e0/frontend/src/main/scala/quasar/std/math.scala#L255

This line of the untyper suggests that if we know the result of a division is an integer, we know both arguments are integers.

Exhibit B:
https://github.com/quasar-analytics/quasar/blob/aeab8f8e92362699aeb3715dba32e0200f39c7e0/frontend/src/main/scala/quasar/std/math.scala#L244

This line of the untyper suggests that if we know that two integers are constants, we *do not* produce an integer by dividing them. So Exhibit A must be incorrect.

Exhibit C:
https://github.com/quasar-analytics/quasar/blob/5624a1c0a23df962646ebf9060b0edaab048757c/frontend/src/main/scala/quasar/std/library.scala#L78

This line of the non-constant part of the typer says we can produce integers from division, if both arguments have been inferred as integers. This is inconsistent with Exhibit B for the same reason.

Both arguments will be inferred as integers, however. This is because working backwards, we infer the argument of `substring` to be an integer, walk back through the untyper to learn that both arguments of the division must be integers through Exhibit A, then check (with the typer) that two integer argument types give us an integer result type. And that's exactly what Exhibit C does. 

The fix seems to be correcting Exhibits A and C by removing `numericWidening` from the typer and making the `untyper` stop pretending we can return `Int` from `Divide`. I don't know exactly how numeric coercion works in the compiler, but this is my best guess.

**Comment by nicflores** [comment]
@edmundnoble and I just verified that his branch, [coherent-stdlib-types](https://github.com/edmundnoble/quasar/tree/coherent-stdlib-types), correctly handles the workaround query mentioned above.

**Comment by edmundnoble** [comment]
To clarify, the workaround query actually does not typecheck on master right now, because there's a feature missing from the typer.

**Comment by jsantos17** [comment]
@edmundnoble that's interesting. I'm sure that query was working when I opened this issue. I wonder if any other changes affected this.

**Comment by edmundnoble** [comment]
Oh actually, I'm miscommunicating. The fix to the Divide problem makes the workaround query not work. It just required a further fix.
