### ISSUE TITLE
`value` wrapping still occurs in the new Mongo connector

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#2762]
This is a bit of a blocker for the structure editor, since the frontend doesn't know when it will need to modify the projection paths to account for the `value`, and that would need special casing per connector too which has its own difficulties... but anyway, the specifics:

Using this example data set:
``` json
{ "a": 1, "b": { "ba": true }, "c": [] }
{ "a": 2, "b": { "ba": false }, "c": [true, false, "maybe"] }
{ "a": 3, "b": { "ba": true }, "c": null }
```

In the structure editor, choosing to "relabel key" `c` as `ccc` will result in a query like this:

``` sql
SELECT OBJECT_CONCAT(DELETE_FIELD(t0, "c"), {"ccc": OBJECT_CONCAT(t0.ccc, t0.c) ?? t0.c}) ?? t0 FROM `/mongo/test/structure_test_simple.json` AS t0
```

Which results in this:

``` json
{ "value": { "_id": { "$oid": "59ba92c22272dc2d3c07ba58" }, "a": 1.0, "b": { "ba": true } } },
{ "value": { "_id": { "$oid": "59ba92c22272dc2d3c07ba59" }, "a": 2.0, "b": { "ba": false } } },
{ "value": { "_id": { "$oid": "59ba92c22272dc2d3c07ba5a" }, "a": 3.0, "b": { "ba": true } } }
```

1. The results are now under a `value` key
2. An `_id` field is now appearing with each "row" under the `value`

`c` and `ccc` are also missing now, but that's probably because the delete succeeded, but re-inserting it failed due to the `value`-wrap.

Issue 1 is not new - old mongo behaved this way too. Issue 2 is kinda new - with old mongo, often a `__tmpN` key would appear under the results with copies of the old values in it, but that may be entirely unrelated to the `_id` appearence - it's just similar in the sense that "new data" is appearing after the query.

For reference, here's the expected result, as returned by `spark-local`:

``` json
{ "a": 1, "b": { "ba": true }, "ccc": [] },
{ "a": 2, "b": { "ba": false }, "ccc": [ true, false, "maybe" ] },
{ "a": 3, "b": { "ba": true }, "ccc": null }
```

**Comment by wemrysi** [comment]
Some thoughts/ideas that came out of discussions between @alissapajer and me regarding this problem:

0. This occurs due to ending up with a value of the proper shape in the aggregation pipeline, either due to a previous stage or even map-reduce, but not having a facility (pre-3.4) to emit that value directly. Instead we are forced to construct an object literal with the desired value at some field, which we choose to call `value`.

1. We should be able to eliminate the `value` wrapping completely in MongoDB 3.4+ via the `$replaceRoot` operator (#2384).

2. For pre-3.4 versions, we could solve this for _streaming_ queries by computing a unique field name with which to wrap values and then eliminate this value as a post-processing step when emitting results. This, however, wouldn't help "write-back" queries where the results are written to MongoDB.

Further investigation of how scenarios requiring `value` wrapping occur in the MongoDB planner may yield a means of restructuring plans to avoid them altogether, but I don't have enough information to say for sure.

**Comment by jdegoes** [comment]
For (2), if we save metadata, it can also help with write-back queries.

The `value` wrapping has been a longstanding pain that is increasingly impossible to workaround in a reliable fashion for the front-end. /cc @zeeiyerWork

**Comment by cryogenian** [comment]
Also this one breaks charting. 
Charts basically does two queries: 
+ `select * from :inputResource` --> `:grouppedResource`
+ `select foo as category, sum(bar) as measure, null as something, null as somethingElse from :grouppedResource group by category order by category` 

Our codecs expect that results are `[{ "category": "string", "measure": number, "something": null, "somethingElse": null}]`. WIth `"value"` wrapper charts are empty

**Comment by cryogenian** [comment]
I encountered performance regression for nested queries with groupping functions. E.g. https://github.com/slamdata/slamdata/issues/2109#issuecomment-329523726

**Comment by wemrysi** [comment]
It turns out the situation is a bit more complicated than I originally thought. It looks like there are 4 scenarios regarding `value` wrapping:

1. A streaming query that results in map-reduce as the final stage. In this case, the documents will look like `{ "_id" : ..., "value": <the actual value>}`, we have no control over the field names, this is just how map-reduce results look.

2. A write-back query that results in map-reduce as the final stage, it will result in a new collection containing wrapped documents as in (1).

3. A streaming query that results in the aggregation pipeline as the final stage and needs to output an object value directly. Prior to `$replaceRoot` in 3.4, there was no facility available to do this so we wrap as `{ "value" : <the actual value> }`, here we have total control over the field name.

4. A write-back query that results in the same situation as (3).

To solve these, in order of priority

(1) Project out the `value` property when streaming back map-reduce results. We know statically when this scenario occurs and that the values are _always_ wrapped as above, so this should be safe and relatively easy to do.

(3)(4)[>= 3.4] Leverage `$replaceRoot` in the aggregation pipeline.

(3)[< 3.4] Use a sigil, `S`, that is far less likely to occur in actual data than `value` to wrap values in the aggregation pipeline and then project it away as a post-processing step in Quasar.

(2)[>= 3.4] Add an aggregation stage after the final map-reduce stage and use `$replaceRoot` to clean up the result, may be a bit of a performance hit as it requires another traversal of the results.

For the < 3.4 write-back scenarios, if we're willing to stipulate that the following only hold if the data we write back isn't modified outside of quasar, then

(4)[< 3.4] Write the values out, wrapped in `S`, and, during query planning, inspect the first document in a collection, looking for the shape `{ S : ... }`. If it is found, update the query plan to add projections of `S` where necessary. This should be safe, given the above stipulation, as we know if _any_ value in a collection is wrapped in `S` then _all_ of them are.

(2) Similar to (4), when writing out a final map-reduce stage, we add a finalizer that nests the result under `S`. When planning a query, we'd then _also_ look at the first document for the shape `{ "_id": ..., { "value" : { S : ...}}}` and add the necessary projections to the query plan if found.

It is also worth noting that these < 3.4 write-back solutions will only work when writing mongo results back to mongo, if/when we implement writing results back to a different connector, we'd need to revisit this.

**Comment by zeeiyerWork** [comment]
As discussed, let's first fix the Mongo 3.4 scenario since a deterministic fix exists via the $replaceRoot operator. Then let's try to squeeze in the < 3.4 solution (and ensure caveats get documented via Release Notes).

**Comment by damonLL** [comment]
Would this issue cause a Pivot Table with dimensions to fail in Mongo? If I group by state with patients data, it fails. If I have no groupings (dimensions) then it succeeds. I'm using the quasar backend rather than slamdata-backend since the latter is not letting me run SD. Here's the query without the aggregation / dimension:
```
CREATE FUNCTION ROUND1(:val) BEGIN FLOOR1(0.5 + :val) END;
CREATE FUNCTION CEIL1(:val) BEGIN FLOOR1(1 + :val) END;
CREATE FUNCTION FLOOR1(:val) BEGIN CASE WHEN (:val % 1) = 0 THEN :val WHEN :val < 0 THEN (:val - :val % 1) - 1 ELSE :val - :val % 1 END END;
CREATE FUNCTION ROUND(:val, :n) BEGIN ROUND1(:val * 10.0 ^ :n) / 10.0 ^ :n END;
CREATE FUNCTION CEIL(:val, :n) BEGIN CEIL1(:val * 10.0 ^ :n) / 10.0 ^ :n END;
CREATE FUNCTION FLOOR(:val, :n) BEGIN FLOOR1(:val * 10.0 ^ :n) / 10.0 ^ :n END;
SELECT row.state AS state, row.last_name AS last_name, row.first_name AS first_name,
row.age AS age FROM `/mongodb/data/patients` AS row
```
Here it is *with* the aggregation / dimension:
```
CREATE FUNCTION ROUND1(:val) BEGIN FLOOR1(0.5 + :val) END;
CREATE FUNCTION CEIL1(:val) BEGIN FLOOR1(1 + :val) END;
CREATE FUNCTION FLOOR1(:val) BEGIN CASE WHEN (:val % 1) = 0 THEN :val WHEN :val < 0 THEN (:val - :val % 1) - 1 ELSE :val - :val % 1 END END;
CREATE FUNCTION ROUND(:val, :n) BEGIN ROUND1(:val * 10.0 ^ :n) / 10.0 ^ :n END;
CREATE FUNCTION CEIL(:val, :n) BEGIN CEIL1(:val * 10.0 ^ :n) / 10.0 ^ :n END;
CREATE FUNCTION FLOOR(:val, :n) BEGIN FLOOR1(:val * 10.0 ^ :n) / 10.0 ^ :n END;
SELECT row.state AS state, [row.state...] AS state_2, [row.last_name...] AS last_name,
[row.first_name...] AS first_name, [row.age...] AS age FROM `/mongodb/data/patients`
AS row GROUP BY row.state ORDER BY row.state ASC
```
So I'm setting this here for now, but I'm happy to open a new SlamData issue for it if folks think that's where it should go?

**Comment by wemrysi** [comment]
@damonLL Yes, it looks like the results of the query involving reductions are wrapped. I'd assume this would cause problems with the pivot table, but I can't say for sure.

**Comment by wemrysi** [comment]
So `$replaceRoot` isn't actually the panacea we were hoping for as we can only use it safely if we know statically that _all_ the values used as replacement are documents, otherwise the query explodes. So even 3.4+ will still make use of the other strategies described above. As a result I'm deprioritizing `$replaceRoot` as it appears to be strictly an optimization in certain cases for 3.4+.
