### ISSUE TITLE
Map vs Object naming in SQL² functions

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#2808]
Maybe we could sort this out a bit? Either by adding both varieties of the functions, or settling on a consistent choice :smile:

Currently there's:
- `OBJECT_CONCAT`
- `MAKE_OBJECT`
- `FLATTEN_MAP`
- `SHIFT_MAP`

Also, we refer to maps having "keys" everywhere, but then the function for deleting them is called `DELETE_FIELD`.

**Comment by jdegoes** [comment]
They should use `MAP` and not `OBJECT`, and `KEY` and not `FIELD`.

**Comment by alissapajer** [comment]
This is straightforward search and replace and won't take very long to do with the right tooling, so I'd like to get this scheduled soon, as it's annoying to have inconsistencies like this because I can never remember the function names.

We'll need to verify both the logical plan and qscript function names. 

I'd also like to make the names across logical plan functions and qscript functions the same, where possible. For example in logical plan we have `ObjectProject` and in qscript we have `ProjectField`. Ultimately we will have just one representation of each function, not two, but for now we should settle on a consistent naming scheme across logical plan and qscript, as well as within each.

**Comment by alissapajer** [comment]
Also, as well handling logical plan and qscript functions, we need to do what the original issue requested, which is make the names consistent in SQL² :)

I just got excited by the chance to fix this in logical plan and qscript as well. We can make a separate issue for that if it doesn't get done at the same time as the `SQL²` names.

**Comment by garyb** [comment]
Since the next release is a major release, maybe we should take this opportunity to do the changes like this one and #2807, since they're potentially breaking to users? Just a thought while the priority of outstanding issues is being discussed - this is definitely not "technically important" but big release time is pretty much the prime opportunity for doing this sort of thing.

I guess it doesn't have to be breaking if old aliases are kept for these functions - or we could migrate workspaces in the frontend, automatically rewriting to the new function names, but yeah... still would be nice to have.

**Comment by alissapajer** [comment]
This could be done pretty quickly so if business is in agreement, we should be able to sneak this issue in during the next few days. /cc @zeeiyerWork 

We need to decide if we're going to keep the old names along with the new for a deprecation period, or if we will just rename the functions, making it a breaking change. On the backend we currently do not have any warning mechanism in place, so we would be unable to provide deprecation warnings; it would be up to us (and our documentation) to tell customers about the deprecations.

**Comment by zeeiyerWork** [comment]
OK scheduled for October and we can discuss. 
Providing a graceful retirement of old function names via a deprecation period is always desirable.

**Comment by jdegoes** [comment]
@garyb @zeeiyerWork Correct me if I'm wrong, but these functions are not actually used by end-users, since they are undocumented and originally intended purely for logical plan generation (desugaring SQL<sup>2</sup>), so I think 5.0 is a good place to break compatibility and this will not cause pain for users right now. Whereas, if we defer to when structure editor starts generating queries containing these function names, we will have to create a migration path forward and deprecation cycle. /cc @alissapajer 

Perhaps @damonLL or @dugdun can chime in to see if any queries they've created or seen use any of these functions.

**Comment by zeeiyerWork** [comment]
Well yeah some of these are used by Structure editor (e.g. `SELECT OBJECT_CONCAT(DELETE_FIELD(t2, "c"), {"test": OBJECT_CONCAT(t2.test, {"c": OBJECT_CONCAT(t2.test.c, t2.c) ?? t2.c}) ?? {"c": t2.c}}) ?? t2 FROM (SELECT OBJECT_CONCAT(DELETE_FIELD(t1, "b"), {"test": OBJECT_CONCAT(t1.test, {"b": OBJECT_CONCAT(t1.test.b, t1.b) ?? t1.b}) ?? {"b": t1.b}}) ?? t1 FROM (SELECT OBJECT_CONCAT(DELETE_FIELD(t0, "a"), {"test": OBJECT_CONCAT(t0.test, {"a": OBJECT_CONCAT(t0.test.a, t0.a) ?? t0.a}) ?? {"a": t0.a}}) ?? t0 FROM `/spark-local/structure_test_deep.json` AS t0) AS t1) AS t2
`
:  So having a graceful degradation period at least decouples as to when frontend changes have to roll. Else they have to be rolled out together given the tight naming dependency. The other question is whether the outside world has deployed modules which reference some of these.

**Comment by garyb** [comment]
Yeah, `OBJECT_CONCAT` and `DELETE_FIELD` are used extensively in the structure editor. We don't use `MAKE_OBJECT` anywhere that I know of.

**Comment by jdegoes** [comment]
@garyb And no one is using structure editor in 4.2.x, so it seems reasonable.
