### ISSUE TITLE
Various structure editor queries result in missing data

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#2958]
A couple of Quasar versions back, I had all 4 of the currently supported structure edit operations working on the Spark local connector, but trying on both mimir and mongo in Quasar 25.0.16 they're not giving the results I'd expect.

Using this dataset:
``` json
{ "a": 1, "b": 2 }
{ "a": 2, "b": 4 }
{ "a": 3, "b": 6 }
```
And this query:
``` sql
SELECT OBJECT_CONCAT(DELETE_FIELD(t0, "b"), {"c": OBJECT_CONCAT(t0.c, t0.b) ?? t0.b}) FROM `/mimir/test-data` AS t0
```
I get this result:
``` json
{ "a": 1 }
{ "a": 2 }
{ "a": 3 }
```
But was expecting:
``` json
{ "a": 1, "c": 2 }
{ "a": 2, "c": 4 }
{ "a": 3, "c": 6 }
```

I can include a few other example queries, but they're of similar form, so I'm pretty sure the problem is arising due to the `OBJECT_CONCAT` and `??` on the inside, as a query like this:

``` sql
SELECT OBJECT_CONCAT(DELETE_FIELD(t0, "b"), {"c": t0.b}) FROM `/mimir/test-data` AS t0
```

Gives the expected result. So maybe it's `IfUndefined` issues again? Although last time was mimir-specific, I think. `OBJECT_CONCAT(t0.c, t0.b)` should definitely be undefined in this case (but we need that in the query for the intended behaviour in cases where `t0.c` does also already exist), so it seems like the `?? t0.b` fallback should be working there.

**Comment by alissapajer** [comment]
I have located the problem in the qscript, quasar v25.0.23
```
│           │  ╰─ MakeMap
│           │     ├─ Constant(Str(c))
│           │     ╰─ Guard
│           │        ├─ Guard
│           │        │  ├─ RightSide     // test-data values
│           │        │  ├─ Type(Obj(Map[], Some(Top)))
│           │        │  ├─ ProjectField
│           │        │  │  ├─ RightSide
│           │        │  │  ╰─ Constant(Str(b))
│           │        │  ╰─ Undefined
│           │        ├─ Type(Obj(Map[], Some(Top)))
│           │        ├─ STUFF
│           │        ╰─ Undefined
```
The `Guard`s are in the incorrect place. The inner `Guard` above will return `ProjectField(RightSide, Constant(Str(b)))` because the `test-data` is an object. But then in the outer `Guard` we check if _that_ projection is an object, which it is not, and so the values populating the `"c"` column all go to `Undefined`.

The `IfUndefined` call is inside `STUFF`. Considering `OBJECT_CONCAT(t0.c, t0.b) ?? t0.b`, we need to check if the type of `t0.c` and `t0.b` are objects (in order to concat them) within the context of the `IfUndefined`. But instead we are checking their types outside that context.

**Comment by garyb** [comment]
Is #2960 perhaps another manifestation of the same problem then?

**Comment by alissapajer** [comment]
Here is the full qscript for reference

<details>
  <summary>qscript</summary>

```
QScript (Optimized):
Map
├─ Subset(Take)
│  ├─ Unreferenced
│  ├─ From
│  │  ╰─ ShiftedRead(/test-data, ExcludeId)
│  ╰─ Count
│     ╰─ Map
│        ├─ Unreferenced
│        ╰─ Constant(Int(11))
╰─ Guard
   ├─ ○
   ├─ Type(Obj(Map[], Some(Top)))
   ├─ ConcatMaps
   │  ├─ DeleteField
   │  │  ├─ ○
   │  │  ╰─ Constant(Str(b))
   │  ╰─ MakeMap
   │     ├─ Constant(Str(c))
   │     ╰─ Guard
   │        ├─ Guard
   │        │  ├─ ○
   │        │  ├─ Type(Obj(Map[], Some(Top)))
   │        │  ├─ ProjectField
   │        │  │  ├─ ○
   │        │  │  ╰─ Constant(Str(b))
   │        │  ╰─ Undefined
   │        ├─ Type(Obj(Map[], Some(Top)))
   │        ├─ Guard
   │        │  ├─ Guard
   │        │  │  ├─ ○
   │        │  │  ├─ Type(Obj(Map[], Some(Top)))
   │        │  │  ├─ ProjectField
   │        │  │  │  ├─ ○
   │        │  │  │  ╰─ Constant(Str(c))
   │        │  │  ╰─ Undefined
   │        │  ├─ Type(Obj(Map[], Some(Top)))
   │        │  ├─ IfUndefined
   │        │  │  ├─ Guard
   │        │  │  │  ├─ ○
   │        │  │  │  ├─ Type(Obj(Map[], Some(Top)))
   │        │  │  │  ├─ ConcatMaps
   │        │  │  │  │  ├─ ProjectField
   │        │  │  │  │  │  ├─ ○
   │        │  │  │  │  │  ╰─ Constant(Str(c))
   │        │  │  │  │  ╰─ ProjectField
   │        │  │  │  │     ├─ ○
   │        │  │  │  │     ╰─ Constant(Str(b))
   │        │  │  │  ╰─ Undefined
   │        │  │  ╰─ Guard
   │        │  │     ├─ ○
   │        │  │     ├─ Type(Obj(Map[], Some(Top)))
   │        │  │     ├─ ProjectField
   │        │  │     │  ├─ ○
   │        │  │     │  ╰─ Constant(Str(b))
   │        │  │     ╰─ Undefined
   │        │  ╰─ Undefined
   │        ╰─ Undefined
   ╰─ Undefined
```
</details>

But it looks like the problem actually lies in the logical plan, and the qscript is the correct representation of the incorrect logical plan.

<details>
  <summary>logical  plan</summary>

```
Rewritten Joins:
Let('__tmp0)
├─ Let('__tmp1)
│  ├─ Read(/mimir/test-data)
│  ╰─ Typecheck(Obj(Map[], Some(Top)))
│     ├─ Free('__tmp1)
│     ├─ Free('__tmp1)
│     ╰─ Constant(NA)
╰─ Invoke(Take)
   ├─ Invoke(Squash)
   │  ╰─ Invoke(ObjectConcat)
   │     ├─ Invoke(DeleteField)
   │     │  ├─ Free('__tmp0)
   │     │  ╰─ Str("b")
   │     ╰─ Invoke(MakeObject)
   │        ├─ Str("c")
   │        ╰─ Let('__tmp2)
   │           ├─ ObjectProject(Free('__tmp0){"b"})
   │           ╰─ Typecheck(Obj(Map[], Some(Top)))
   │              ├─ Free('__tmp2)
   │              ├─ Let('__tmp3)
   │              │  ├─ ObjectProject(Free('__tmp0){"c"})
   │              │  ╰─ Typecheck(Obj(Map[], Some(Top)))
   │              │     ├─ Free('__tmp3)
   │              │     ├─ Invoke(IfUndefined)
   │              │     │  ├─ Invoke(ObjectConcat)
   │              │     │  │  ├─ Free('__tmp3)
   │              │     │  │  ╰─ Free('__tmp2)
   │              │     │  ╰─ ObjectProject(Free('__tmp0){"b"})
   │              │     ╰─ Constant(NA)
   │              ╰─ Constant(NA)
   ╰─ Constant(Int(11))
```
</details>

**Comment by alissapajer** [comment]
It's interesting that these operations were working before. I wonder if we corrected a bug in qscript, and by doing so exposed a bug in logical plan.

**Comment by alissapajer** [comment]
The logical plan looks correct up to the typechecking phase, so I believe the bug is introduced there.

**Comment by rabbitonweb** [comment]
@alissapajer so the error seem to be in incorrectly generated qscript, correct?

**Comment by alissapajer** [comment]
@rabbitonweb the qscript is incorrect because the logical plan that is handed to the qscript compiler is incorrect. So to fix this you won't have to touch the qscript compiler.

**Comment by rabbitonweb** [comment]
just logical plan?

**Comment by alissapajer** [comment]
@rabbitonweb yeah, so there are a handful of compiler phases that rewrite the logical plan. This bug is in the typecheck phase, which is one of the phases that rewrites logical plan. 

This phase is run (and printed from) here https://github.com/quasar-analytics/quasar/blob/master/core/src/main/scala/quasar/package.scala#L74 so the bug is in `ensureCorrectTypes`.

**Comment by alissapajer** [comment]
Currently we are checking the type of `ObjectProject(Free('__tmp0){"b"})` _outside_ the context of the `IfUndefined`. But if the left side of the `IfUndefined` is actually undefined (which in this example it always is), then we need to default to `ObjectProject(Free('__tmp0){"b"})`, and there is no type requirement for the default expression because it is being inserted into a map: `{"c": t0.b}`.

**Comment by zeeiyerWork** [comment]
Spoke to @garyb: Structure editor is not really usable without this issue being fixed. Hence the skull. (Structure editor was committed to as part of 5.0.0 deliverable - see  https://docs.google.com/presentation/d/1rH1scFJTGV2YPL40WxAj2HbS1gl03E6GxL_FJ6PFz6U/edit#slide=id.g24666aeab3_0_4. The doc refers to 5.0.0 as still 4.3.0 since its been around for a while).

**Comment by rabbitonweb** [comment]
Ok, I have general understanding why it does not work. I know what should be fixed in LP in ordr to make it work. I don't know yet how to fix it in LP.

**Comment by rabbitonweb** [comment]
I've added some tests but they are stahed in my local branch because they need to be rewritten. I have understanding of how`inferTypes` works, I have vague understanding (very vague) how `checkTypesƒ` - once I get that I will try to tackle the issue. Could not really pair with anybody on it for the past two days, maybe I will have luck today.
