### ISSUE TITLE
Error when converting MongoDB ObjectId to String

### ISSUE THREAD

**Issue by dugdun** [quasar-analytics/quasar#2974]
Quasar Version: 25.0.24

In newer versions of Quasar if you run the following query:

```sql
select to_string(`_id`) from `/mongodb-3.4/data/patients`
```

you will get the following error:

![screen shot 2017-10-24 at 15 40 29](https://user-images.githubusercontent.com/828514/31969400-b66e8136-b8d1-11e7-979c-3d4c89feb4fa.png)

In Quasar 20.14.7 (shipped with SlamData 4.2.6) this worked as expected:

![screen shot 2017-10-24 at 15 42 30](https://user-images.githubusercontent.com/828514/31969483-01d72542-b8d2-11e7-9f47-3a6d5d0489d9.png)

**Comment by jdegoes** [comment]
Let's make sure this ships with a test to prevent breakage in the future.

**Comment by jsantos17** [comment]
So it looks like the undocumented hack in #2453 does not convert `ObjectId` to `String`. Simply disabling that `ToString` is not enough to fix this as `ToString` for `JsCore` also appears to be broken as well. There are at least two ways I can fix this:

1. Disable the `ToString`  undocumented hack and fix the`ToString` for `JsCore`.
2. Refactor the `FuncHandler` typeclass to handle multiple layers of `MapFuncCore` instead of a single layer as it currently is. That way we could match on `ToString(ProjectField(Hole, Constant(Str(_id))))` and handle it separately from just `ToString`. That'd involve changing types from `MapFunc[T, ?] ~> OptionFree[EX, ?]` to `T[MapFunc[T, ?]] => OptionFree[EX, Fix[ExprOp]]`

The second solution is less of a workaround but would take significantly more time. Anyway, we still need map-reduce for this. As far as I know, there's no way to convert `ObjectId` to `String` in the aggregation pipeline. Happy to be proven incorrect.

What do you think @rintcius? Is number 1 an acceptable solution to this? Any other ideas on how to fix this?

I'm inclined to implement number 1 given the importance of having this working in a timely manner. I can see number 2 taking a week or two to implement.

**Comment by rintcius** [comment]
How about moving `ToString` impl. to `handleSpecial`? Here we do have access to the layers

**Comment by jsantos17** [comment]
I understand `handleSpecial` is not versioned, so we'd need to use the deprecated `$substr` as it's the only "safe" operation for Mongo 3.2 we can use to implement the undocumented hack. So we would need to version `handleSpecial` to avoid usage of deprecated functions. Or is there a different way to implement this?

**Comment by jsantos17** [comment]
I'm also wondering if this hack has other unknown corner cases. It's definitely a risk to rely on undocumented behavior. It has already burnt us once (here) so we really want to reconsider if optimizing some `ToString`s is worth the risk and effort.

This can theoretically stop working after minor updates with no warning, can't it?

**Comment by rintcius** [comment]
Yeah, it's not versioned, but I think using `$substr` for `ToString` would be ok for now, since it would both enable `to_string` for ObjectId's and still avoid MR for `to_string`s where it can. 

We can add a TODO to make it versioned.

I think this burnt us just because we didn't cover it in the tests. Adding a test for it should prevent this failing again.

**Comment by jsantos17** [comment]
So I followed your advice @rintcius and will use `$substr` for now and leave a `FIXME` and test that'll detect when this breaks. However, there are at least three bugs preventing this from working:

1. Undocumented hack using `$substr` to convert to string does not work for `ObjectId`.
2. JS `ToString` does not handle `ObjectId` properly.
3. Usage of `to_string(_id)` first typechecks `_id` to be `Type(Null, Int, Dec, Interval, Str, Timestamp, Date, Time, or Bool)` which doesn't match `ObjectId`, hence the result is `undefined`

Example QScript with the problematic typecheck:

```
QScript Mongo (Prefer Projection):
Map
├─ ShiftedRead(/jps/zips, ExcludeId)
╰─ Guard
   ├─ ProjectField
   │  ├─ ○
   │  ╰─ Constant(Str(_id))
   ├─ Type(Null, Int, Dec, Interval, Str, Timestamp, Date, Time, or Bool)
   ├─ ToString
   │  ╰─ ProjectField
   │     ├─ ○
   │     ╰─ Constant(Str(_id))
   ╰─ Undefined
```

I have handled the first two issues, but the third one is a bit more complicated. I can think of three ways to fix number 3:

1. Rewrite the plan to elide the `Guard` when we're projecting `_id` out of `SrcHole` inside a `ShiftedRead`.
2. Rewrite the plan to add `ObjectId` to the list of types when we typecheck against `Type(Null, Int, Dec, Interval, Str, Timestamp, Date, Time, or Bool)`.
3. Add a special case for `Guard` for JS to add `ObjectId` as one of the allowed types when typechecking `Type(Null, Int, Dec, Interval, Str, Timestamp, Date, Time, or Bool)`.


Any other ideas? cc @wemrysi, @djspiewak, @alissapajer?

**Comment by jsantos17** [comment]
So I delved a little into the Mongo source to see how this undocumented hack actually works and discovered this doesn't work for booleans either: 

```javascript
db.days.aggregate([{$project:{ "0": {$substr: [true, 0, -1] }}}])
```

This errors, just like with `ObjectId`. [Relevant code](https://github.com/mongodb/mongo/blob/ee6b784fecd5a8e8717a7a17a78a0d54535c5df7/src/mongo/db/pipeline/value.cpp#L583). I still advocate for not using this hack and instead suggest planning `ToString` using JS, just like old Mongo does.

**Comment by rintcius** [comment]
`$substr` doesn't work for booleans and null as well, but they are also not used for `to_string`. Here's the function that is used: https://github.com/quasar-analytics/quasar/blob/834fab03747853c87eea6850ae91112e9881935a/mongodb/src/main/scala/quasar/physical/mongodb/expression/ExprOpCore.scala#L390-L400

Having to use a hack is of course not all that desirable, but it still needs an actual code change of the mongo software to make it start breaking on our side. We are not the only one relying on this behaviour, so I don't expect it will change in a patch version.

I think the win of avoiding map-reduce is worth using this hack, but let's ask @jdegoes to decide.

**Comment by djspiewak** [comment]
@jsantos17 Regarding your question, I'd say option 3 sounds the best to me.  OID isn't a real type in Quasar-land, so allowing it when we require "String" seems correct.

**Comment by jdegoes** [comment]
OK to hack to avoid using map/reduce. 👍 

map/reduce makes queries unusable. We can be more picky about semantics later.

**Comment by jsantos17** [comment]
Thanks for all the feedback. I'll restore the hack to use `$substr`. Looks like @rintcius was way ahead of me with `mkToString` :). Also following @djspiewak advice on typechecking `Syntaxed` as a special case.

**Comment by jsantos17** [comment]
So after discussing what's the best way to implement `to_string` with @rintcius and @wemrysi, we have a few options:

1. Use the approach in my PR: #3012. We plan `to_string` using aggregation, except when it's on a projection named `_id`. This isn't ideal as we rely on the field name string (`_id`) to plan. Calling `to_string` on fields with names other than `_id` and an `ObjectId` type **will not work**. @dugdun, @damonLL: is this implementation useful enough?

2. Ask the user for more information so we can plan correctly, i.e introduce a function named `oid_to_string` and always handle that function in `mapReduce`. This is very Mongo-centric, not sure if we want to introduce such a function in SQL².

3. Go with the old Mongo approach: Plan every `to_string` using `mapReduce`. This might make queries unusable, but is more reliable than 1. 

I'd like to hear @jdegoes /@zeeiyerWork's opinions since there are some business trade-offs here.

**Comment by dugdun** [comment]
@jsantos17 in regards to number one above, why would this only work for fields named `_id`? I would think that we would want to be able to convert any field that was an ObjectID to a string. Having it only work on fields named `_id` would make it seem broken when used on any other field that stored an ObjectID value.

Since old Mongo was using `mapReduce` to process the `to_string()` functionality on ObjectID fields, I don't know that option three will be any more unusable that it was in the past.

**Comment by jdegoes** [comment]
It's true that (3) is not less usable than present. Would be interested in why (1) has the stated limitation.

**Comment by jsantos17** [comment]
@jdegoes @dugdun we need to somehow avoid aggregation when the input is an `ObjectId`. I don't really see any way we can tell statically if a `ToString` needs `mapReduce` or not, so I special cased it to plan with `mapReduce` when the input field is named `_id`.

**Comment by jdegoes** [comment]
Perhaps TO_STRING may assume non-object ID and we add the oid_to_string function specifically for MongoDB. This gets us performance, albeit it will surprise users because TO_STRING will not work for OID types. @dugdun @damonLL ???

**Comment by zeeiyerWork** [comment]
There is pressure from the business around time-to-market on this. So 1 suggestion is to live with the fact that for now we assume that ObjectIds are named "_id". We can later relax the constraint via the suggestion to have a separate Oid_to_string. The standard 80-20 compromise to meet time-to-market constraints. 
![image](https://user-images.githubusercontent.com/24783629/32503451-1857f02e-c392-11e7-9983-1d6d10109f5e.png)
![image](https://user-images.githubusercontent.com/24783629/32503470-20e1a1b8-c392-11e7-96b6-448aed88e927.png)

**Comment by jdegoes** [comment]
@zeeiyerWork IMO that does not solve the problem in a better way than a custom function `OID_TO_STRING`. A custom function lets us assume that `TO_STRING(x)` will only be called on non-OID values `x`, which allows for an efficient implementation, requiring only that `OID_TO_STRING` compile down to map/reduce.

Note that any use of `OID_TO_STRING` may not be usable in a production workflow. Customer expectations must be set realistically to avoid setting them up for failure.

**Comment by djspiewak** [comment]
`OID_TO_STRING` can also be done as a derived mapfunc, just deriving to `TO_STRING` on every connector except mongo.

I mean, I think it's pretty terrible to introduce something like this into SQL^2, but it's *doable* without massive disruption to other parts of the codebase.

**Comment by jdegoes** [comment]
@djspiewak It is horrible.

We need:

1. Backend-specific "types".
2. Backend-specific functions.

`OID` should not contaminate other connectors, neither should `OID_TO_STRING`.

**Comment by djspiewak** [comment]
I agree we need those things to solve this in general.  We're a very long way from that though, unfortunately.

**Comment by jsantos17** [comment]
After talking with @dugdun and @zeeiyerWork we agreed to go with matching on the `"_id"` string. i.e option 1 [here](https://github.com/quasar-analytics/quasar/issues/2974#issuecomment-342258453).
