### ISSUE TITLE
Improve mongo's assumeReadType

### ISSUE THREAD

**Issue by rintcius** [quasar-analytics/quasar#3014]
Currently mongo's rewrite step `assumeReadType` does not traverse across branches which leads to queries doing type-checks unnecessarily. 

Moreover, this rewrite is not traversing `Sort` nodes, also leading to unnecessary type-checks.

In both cases queries may end up doing map-reduce because of these checks.

**Comment by jsantos17** [comment]
Given the many problems we have with `assumeReadType`, it might be worth considering changing how we insert typechecks instead of trying to fix "bad" typechecks after the fact. 

I know @edmundnoble has been working with the typechecker, so he might know how hard it might be to avoid inserting this typecheck in a per-connector basis. 

Specifically, how hard would it be to provide the typechecker with the information that `Read(/mngo/jps/zips)` has type `Obj(Map[], Some(Top))` and avoid inserting the typecheck altogether? In this plan:

```
Optimized:
Let('__tmp0)
├─ Invoke(Squash)
│  ╰─ Read(/mngo/jps/zips)
╰─ Sort
   ├─ Free('__tmp0)
   ├─ ObjectProject(Free('__tmp0){"city"})
   ╰─ SortDir(Ascending)

Typechecked:
Let('__tmp0)
├─ Invoke(Squash)
│  ╰─ Let('__checku0)
│     ├─ Read(/mngo/jps/zips)
│     ╰─ Typecheck(Obj(Map[], Some(Top)))
│        ├─ Free('__checku0)
│        ├─ Free('__checku0)
│        ╰─ Constant(NA)
╰─ Sort
   ├─ Free('__tmp0)
   ├─ ObjectProject(Free('__tmp0){"city"})
   ╰─ SortDir(Ascending)
```

**Comment by wemrysi** [comment]
@jsantos17 It's definitely worth it, see #2387 for some more detail.

**Comment by edmundnoble** [comment]
@juanpablo there have been prior suggestions by @djspiewak to add an optional argument to `Read`, the expected type to be read. In this case, it seems like it wouldn't help, because only the Mongo connector knows that objects are the only results of `Read` calls; it seems like you need to remove `Guard` nodes around `Read` nodes when you see them in the connector.

**Comment by jsantos17** [comment]
@edmundnoble how about adding another property to the `BackendModule` trait specifying the `Read` type? We could then pass this type to the typer. 

Currently we're trying to remove the `Guard` nodes as you say, but this is proving time consuming and error prone.

**Comment by edmundnoble** [comment]
It seems like that may be possible, during the LP compilation phase. However, I'm not familiar with the intersection point between LP/QScript/BackendModule/main.scala, and some major plumbing changes may be needed. It could be that all that's needed is adding an extra parameter to the typecheck phase and an extra field to BackendModule; not sure what kind of design implications that will have, I believe @djspiewak knows more about this area.

**Comment by djspiewak** [comment]
Reading over this thread again and answering the later question…  Doing this by adding a parameter to `BackendModule` is going to be almost impossible, just because of all the re-plumming it would require in LP.

I would guess that the best way to do this *quickly* is for the mongo connector to have a quick rewrite over the qscript it receives to factor out and/or remove some of these scenarios.  Not sure how identifiable these cases are in general.

**Comment by rintcius** [comment]
@djspiewak - note that there's a PR of this already #3001 (indeed in mongo conn. for now)
I have just created an associated issue for this because of a discussion in BE meeting yesterday.

**Comment by wemrysi** [comment]
@djspiewak Are we discussing two different things here? I think what @jsantos17 and I are suggesting is obtaining type information from a connector as to what the actual (not expected) type of values from a read are. This doesn't seem necessary to do during LP read, maybe not even desirable as it would introduce a connector dependency during that phase. Are you asking for the `Read` to be annotated with its inferred type based on usage in the rest of the plan? That definitely sounds useful.

For the former, we could ask for a function from connectors that returns an optional type given a path and use that during typechecking to only create necessary guards. We might also consider separating typechecking and guards altogether, making the latter an optional transformation since connectors like Mimir don't even need them.

**Comment by djspiewak** [comment]
Ah I was speaking of the latter.  It appears I just misunderstood what you guys were asking for.  it seems like to satisfy the former, the best thing would be to add it to the filesystem algebra.  That would allow typechecking to read the type of the dataset (maybe getting `None`) and work off of that baseline, but it would introduce a somewhat annoying dependency on the filesystem of the underlying connector in the LP typecheck phase, which would be hard to thread through.
