### ISSUE TITLE
QSU  source merging must only consider reachable subgraph

### ISSUE THREAD

**Issue by alissapajer** [quasar-analytics/quasar#3055]
We allow for orphaned nodes in a `QSUGraph`, which are defined as nodes contained in the `vertices` but not reachable from the `root`. When source merging computes the graph intersection of two `QSUGraph`s, it must do so against only the vertices reachable from the `root`.

Technically we never need to preserve orphan nodes in a `QSUGraph`, meaning all nodes in `vertices` could be definitionally reachable from the `root`. This isn't something we're expressing at the type level, so the current solution is to prune graphs only when algorithmically necessary. But we do have the option of enforcing this universally at the value level (or encoding it at the type level, though that will probably require more work than we have time for now).

**Comment by djspiewak** [comment]
Rather than finding common sources by intersecting graphs, shouldn't we instead walk the graph to the least-upper bound?  This is immune to orphans, and it's a relatively well understood algorithm from a compsci standpoint (since it is equivalent to LUB computation in systems with nominative subtyping).
