### ISSUE TITLE
Fix (or remove) overly-fragile planner specs

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#3090]
The poster child here is mongo's `PlannerSpec`, which has completely broken under qsu.  Some of that is probably just because qsu is producing terrible qscript right now, but we're very rapidly going to get to a point where these tests are just going to be overly-specific.  They should probably be rephrased in terms of @edmundnoble's DSL, with only a couple very general tests remaining.

Couchbase also has some tests like this, btw.

This is a blocker for landing in master, since the unit tests won't run so long as this is broken.

**Comment by rintcius** [comment]
This relates to #2802 

I agree that `PlannerSpec` should only have a couple of basic tests (I'm right now porting some of the queries to the qscript DSL and it's a pain for larger queries). For the more complex queries we can start _tracking_ the plans of the ITs (the `.test`). Compared to `PlannerSpec` this is both more useful and less work to maintain.

**Comment by rintcius** [comment]
I'm picking this up in favour of #3080 as this is more urgent and useful. 

@djspiewak Shall we discuss once you are online (and had your coffee)?

**Comment by rintcius** [comment]
@djspiewak So I'll work on making the tests less fragile. E.g. assert that there's no Map Reduce, assert max. number of pipeline stages, check for a certain stage etc.

Apart from this, I think we should also verify whether the sql^2 that's tested in the `PlannerSpec` is being tested in IT & if not add it there, otherwise it's going to be difficult to ensure their correctness after QSU has landed. Agree or do you see a better way?

**Comment by djspiewak** [comment]
Agreed.
