### ISSUE TITLE
Extract mappable region from reduce source into reducer

### ISSUE THREAD

**Issue by wemrysi** [quasar-analytics/quasar#3129]
`QSReduce` nodes expect to apply buckets and reducers to a common source, which means we need to extract the mappable region from the source of an `LPReduce` and push it into the reducer, otherwise the buckets are applied to the value to be reduced and not its source.

**Comment by djspiewak** [comment]
@wemrysi Proposal: I think we should remove the ☠️ once my branch lands, since I'm extracting mappable regions for anything that is mergeable, and anything that is not-mergeable and trivial should be handled by the old qscript rewrites.  We should eventually implement this in qsu, but I suspect we won't need it *now*.

**Comment by wemrysi** [comment]
@djspiewak I actually finished implementing this yesterday, should see a PR sometime this morning.
