### ISSUE TITLE
Sorting by string length then limiting doesn't seem to work

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#3154]
https://gist.github.com/5c82fcbba6a902f0a54cff8076fcef49

On the `qsu` branch

If I remove the `limit 5`, I get a *different* set of results, but still not really sorted by `length(city)` (there are shorter city names that don't show up in the top 10).  So that's a bit puzzling.  Sorting by `city` seems fine, but `length(city)` not so much.

This query works fine on other connectors, so I'm tempted to blame mongo.

**Comment by djspiewak** [comment]
This looks like another exemplar: https://gist.github.com/9e9448ef9ba972f5ba563741f4e44ce1  It's almost like sorting in general isn't working?

**Comment by djspiewak** [comment]
And another exemplar: https://gist.github.com/cc5cdae45b1917ccb9f2c709ce25fff5

**Comment by jsantos17** [comment]
I have a good idea on what's happening here. Reductions are planned as a `GroupBuilder` followed by either a `DocBuilder` or a `ExprBuilder`. The pick of between the two is made by checking if the reduction's `Repair` matches the `StaticMap` extractor. 

Right now `repair` will never match `StaticMap` since we don't lookup the `ReduceIndex` into the buckets/reducers before we attempt to match. Therefore reductions will be planned with `GroupBuilder` followed by `ExprBuilder`, always. The problem with `ExprBuilder` is that we don't know its shape so we can't rewrite the references in the following `$sort` to match what the reduction produces. This leads to dangling references after every reduction.

So we need to fix two things:

1. Make sure we plan reductions with `GroupBuilder` + `DocBuilder` whenever we can infer the shape of the results from the repair function. This would give us immediate relief on most queries involving reductions followed by other transformations (such as `$sort`)

2. Figure out how to rewrite references after a `ExprBuilder`. I'm not even sure this is possible, but this is a valid codepath in the connector.

Regarding number two I have a question for @alissapajer, @djspiewak and @wemrysi:

Is it possible that we don't know the resulting shape of a reduction? i.e can we have a `Reduce` with a `repair` FreeMap that doesn't match `StaticMap`?

**Comment by djspiewak** [comment]
Arbitrary, Last or First would return results that we wouldn’t know statically. Also anything that references the buckets in the repair.

**Comment by alissapajer** [comment]
@jsantos17 qscript doesn't provide any guarantee about the shape of the `repair` in a `Reduce`. 

During qscript compilation, if a `repair` is providing access to multiple reduction values or buckets, then the `repair` will indeed be a `StaticMap`. If a `repair` is providing access to just a single reduction, that value will not be wrapped in a `StaticMap`. But this is _only_ during internal qscript compilation, and qscript doesn't guarantee this property once the qscript is compiled and provided to a connector.

Furthermore, once qscript is compiled (and during compilation), it can be rewritten. So it's possible for a `repair` to be rewritten into any other `FreeMap`, depending on the goal of the rewrite. For example, if we have a qscript `Map` node wrapping a `Reduce`, then the mapping `FreeMap` could be rewritten into the `repair` of the `Reduce`, removing the `Map` node entirely, and so the `repair` could take on any shape.

**Comment by alissapajer** [comment]
@jsantos17 above I was talking about "generic" qscript, but maybe there some mongo-specific qscript rewrites that would help in this situation? For example, we could rewrite the qscript so that the `repair` _is_ in a certain shape that would help you.

**Comment by alissapajer** [comment]
Also, :+1: to @wemrysi 's suggestion about using `Outline`.

**Comment by jsantos17** [comment]
@alissapajer it'd way easier if `repair` were a `StaticMap`. I'll try @wemrysi `Outline` suggestion and see what it gets me.

**Comment by alissapajer** [comment]
@jsantos17 is this an issue for _all_ reductions? In the simple query `select sum(pop) from zips`, the only way you could have a `StaticMap` in the `repair` would be if you explicitly wrap the `repair` with a `MakeMap` and then wrap a qscript `Map` around the `Reduce`, projecting out the field you just created.

**Comment by jsantos17** [comment]
@alissapajer not all. The way we infer the shape of the reduction results is based on the `repair` function. There's definitely room for improvement there (`Outline`) as you pointed out.

**Comment by zeeiyerWork** [comment]
based on discussion with @jsantos17 -> any sort after groupby (distinct too implemented as group by in mongo) will be affected - hence skulling.
