### ISSUE TITLE
mongodb: handle all cases for DistinctBy with sorted input

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#378]
As of #284, WorkflowBuilder introduces a second SortOp as needed after grouping for distinctBy, but it only recognizes certain patterns in the source workflow. Handling every case will require rewriting the source workflow.

As far as I know, all the cases that can be produced by SQL queries are handled, but if LogicalPlan is exposed as an API, it would become possible to hit this.

See pending WorkflowBuilder test.

**Comment by sellout** [comment]
I’ve since added a case for `$sort; $project` where the project doesn’t expose `$$ROOT`, but all the fields used in the sort are exposed under some name. There is still a case where we need to modify the project to get access to the fields and then re-insert the original projection post-distinct … and probably other non-`$sort; $project` cases.

**Comment by sellout** [comment]
The “distinct and sort with intervening op” test currently passes also (which was pending this ticket), but was never noticed because workflows have changed so much that the working version didn’t match the expected output.
