### ISSUE TITLE
integration tests: run generated JS

### ISSUE THREAD

**Issue by sellout** [quasar-analytics/quasar#529]
We should run both the regular evaluator as well as the generated JS and check both results. There is currently a case (#528) where we generate bad selectors in the JS output, but I only noticed it trying to debug a different issue, since the only time we check the JS output is when we manually try to run some of it in a Mongo session.

**Comment by mossprescott** [comment]
This is a good idea, especially since we clearly have some interest in capturing our MongoDB JS output for use elsewhere (see #542).

It looks like there's no easy way to run JS commands through the Java API, and anyway that wouldn't give a convincing test of the actual use case, so I think our best bet is to launch the mongo shell from our regression test, passing the commands as input, and parsing the output stream. Fun stuff.

At the same time, we might want to revisit the way we handle temp collections in the generated JS. Right now, they get names like `tmp.gen_0`, instead of the unique names we generate when executing the plan via the API.
