### ISSUE TITLE
compiler: standard library type-checking is weak, lacks coverage

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#571]
Lots of non-sensical queries get through type-checking and fail either in the planner or in MongoDB.

For example:
- `1 < timestamp '...'`: is typed as `Bool` and mongo will evaluate it non-sensically
- `1 + 'abc'`: is assigned the constant type `1`

There are many interesting cases and it should be possible to write unit tests, but we currently have none. Coverage indicates that existing test hit only a small portion of the code.

**Comment by jdegoes** [comment]
The first type is correct, the 2nd one is obviously bogus. Need a much better test suite.

**Comment by mossprescott** [comment]
I would have expected mixed-type comparison to fail, so I went looking for docs on SQL implementations, and man is that a minefield of implicit conversions. I think it's going to be difficult or impossible for us to behave like the RDBMSs in this area. For example, read http://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements002.htm and weep. A key behavior is using type information from a column named on one side of an operator to infer the type for a string constant on the other side. This is why users think they can write `ts < '2015-01-15 ...'`, because Oracle will implicitly convert the rhs with `TIMESTAMP`.

The question is what semantics do we want? If `1 < timestamp '...'` is Bool, what is its value? I don't think we want to leave it up to MongoDB, because [its rules are pretty ad hoc](http://docs.mongodb.org/manual/reference/bson-types/#comparison-sort-order).

**Comment by jdegoes** [comment]
Good point. If we define a total ordering on our `Data`, then mixed comparisons make sense and should be valid. The main reason I can think of to allow such a total ordering is to allow sorting by fields which may be heterogeneous. If you don't have a total ordering, you can't sensibly define such a thing. If you do  have a total ordering, then not only can you define semantics for sorting heterogeneous fields, but to be consistent you must also allow comparisons of fields of differing types.

**Comment by mossprescott** [comment]
Yes, sorting heterogeneous values is a nice feature and I can see where following that line of thinking got MongoDB as well.

However I think we'll probably need to adopt the backend's total ordering (or else we'll have to generate byzantine type comparison expressions where we now have simple applications of the native operators). From the link in my previous comment, here's the list (smallest first): 
> Null
> Numbers (ints, longs, doubles)
> Symbol, String
> Object
> Array
> BinData
> ObjectId
> Boolean
> Date, Timestamp
> Regular Expression

Now, I suppose that's as good as any ordering (although I've always been fond of Python's "sort lexically by the name of the type" rule), but when the next backend has a different list, is it ok for SlamEngine to be inconsistent across them?

@sellout: You shouldn't be missing this fun discussion.

**Comment by mossprescott** [comment]
Another error (which will probably get fixed in #565):
`case when a = 1 then 'ok' else 'reject' end` is typed as the constant `'ok'`

**Comment by jdegoes** [comment]
In the short-term, inconsistency is fine because it leads to far better performance and simpler code, and only divergence in the sole case of heterogeneous types.

Now personally, I'm a fan of sorting by information content: null always comes first, because it holds 0 bits. Then comes boolean, because it holds 1 bit. Etc. Object is a generalization of Array, etc. At the very end, you have Binary, because it holds any number of bits which have no particular structure at all.

**Comment by sellout** [comment]
And to help users avoid heterogeneous comparisons, we should probably add some sort of `typecase` function to the standard library. Or do we already have some way to handle that?

My own inclination is to prevent heterogenous comparisons in the LogicalPlan, because they generally don’t make any sense, and if we want reasonable performance on them, we basically just have to do what each backend does, so we don’t even have any consistency, so why bother sorting? Then (using `typecase`) we can insert SQL’s implicit conversions into the LogicalPlan where necessary (inference + future schema guessing hopefully make this not too terrible†), and users can explicitly homogenize their heterogenous fields (also using `typecase`).

[†] It would also be nice to emit a style warning when a user does something like `ts < '2015-01-15 ...'`, suggesting that they explicitly use a timestamp constant rather than relying on implicit conversion.
