### ISSUE TITLE
compiler: typecheck is wrong for some Coproduct cases

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#572]
`Type.typecheck` gets confused by Coproduct types (for example, apparently accepting any type when any coproduct is expected). See pending tests marked with this issue number.

The source of confusion seems to be related to dealing with Product types, and I believe this code could be greatly simplified by eliminating Product, which is too general to represent the cases we actually need.

Types like `Int & Str` make no sense and are effectively equivalent to `Bottom`, since they can never be inhabited. The only Product types that actually make sense are strict combinations of field types or of element types (because an object can have multiple fields, and an array can have multiple elements). Therefore I suggest we replace Product with an "object" type with zero or more fields (possibly unnamed), and an "array" type with zero or more elements (possibly with unknown indices).

**Comment by jdegoes** [comment]
Yes, Product is too general, although if the implementation is correct it shouldn't matter (basically, since we have `Bottom` in there, any inconsistent product is equivalent to `Bottom` and should behave that way under type checking, lub, glb, etc.). If changing makes the implementation simpler, I'm all for it, though I suspect that having two different product types will not in fact make the implementation simpler (but am happy to be proved wrong!).
