### ISSUE TITLE
planner mongodb array semantics leak through into slamsql

### ISSUE THREAD

**Issue by pjaffe** [quasar-analytics/quasar#589]
My understanding is that the following query should give me 1 result row for each unique combination of "orgRole" values in the subdocuments within the "affiliations" array:
```
SELECT DISTINCT affiliations.orgRole, COUNT(*)
  FROM "/SampleArrayObjects" 
 GROUP BY affiliations[*].orgRole
```
However, the results seem very wrong to me, and I can't figure out what it represents.

If I try the following, I get an ObjectConcat exception.
```
SELECT DISTINCT affiliations[*].orgRole, COUNT(*)
  FROM "/Scratch" 
 GROUP BY affiliations[*].orgRole
```
Two other flavors of this query return results I expect...
If I exclude the "COUNT(*)" as below, I get the expected unique combinations of orgRole:
```
SELECT DISTINCT affiliations.orgRole
  FROM "/SampleArrayObjects" 
 GROUP BY affiliations[*].orgRole
```
If I reintroduce the "COUNT(*)" but remove the "[*]" array designator from the GROUP BY expression, then I get the expected results.  But my understanding is that the [*] really should be specified.
```
SELECT DISTINCT affiliations.orgRole, COUNT(*)
  FROM "/SampleArrayObjects" 
 GROUP BY affiliations.orgRole
```

Here is my sample data to be loaded into a "SampleArrayObjects" collection:
```javascript
{"_id":"1","affiliations":[{"orgId":"1","orgRole":"Student","_id":"1"}]}
{"_id":"2","affiliations":[{"orgId":"2","orgRole":"Student","_id":"2"},{"orgId":"2","orgRole":"Instructor","_id":"3"}]}
{"_id":"3","affiliations":[{"orgId":"1","orgRole":"Student","_id":"4"}]}
```

**Comment by jdegoes** [comment]
Because `affiliations` is an array, the expression `affiliations.orgRole` should always produce `undefined` values in SlamSQL. The reason it does not is because we just haven't gotten around to it. 

MongoDB has some "magic" that allows projection to work on arrays by projecting out their elements. It's unlikely we'll support this because SlamSQL provides other mechanisms to do the same thing, which are built on a well-defined foundation.

We can look into why this is causing unexpected results, but because we do not support MongoDB's magical handling of arrays, we would only issue a fix if this revealed some other deeper problem in the query planning which could cause a problem in supported queries.

As I think about it more, these queries should fail in type checking, but the reason they don't is probably because we don't unify across the different clauses of SQL (and there's a ticket to track that somewhere).

**Comment by pjaffe** [comment]
I just realized that #587 probably tracks the underlying issue here, and I assume that once that is fixed, I should just be running the following query, and not be trying to do any of the other forms (other than removing the "COUNT(*)" if I didn't care about the counts):
```
SELECT DISTINCT affiliations[*].orgRole, COUNT(*)
  FROM "/Scratch" 
 GROUP BY affiliations[*].orgRole
```

**Comment by jdegoes** [comment]
Yes, that's right -- that's definitely the goal! Although this ticket will be useful for tracking these other issues.
