### ISSUE TITLE
mongodb: handle concat where types are not apparent

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#637]
As of #600, the `||` operator can handle concatenating either array or string values, but only if the planner can determine which type of value is involved statically.

That means queries like these work: `select loc || [ pop ] from zips` or `select city || ', ' || state from zips`.

But a query like this does not: `select city || state`. More confusingly, `city || state || '...'` also doesn't work, just because the operator is left-associative.

We could fix this by using type information from elsewhere (the rest of the query or schema inference), or by handling it with a type check in JS (which would force it into map-reduce, even if the values end up being strings).

**Comment by jdegoes** [comment]
A query like `city || state` is not very realistic, it would be much more common to find something like, `city || ', ' || state`, which should allow inference.

Is this operator left-associative in Postgres? We should match that. 

In any case, it shouldn't matter for type inference, because during push down, you'd end up with (A || '...'), which would force `A` to be `String`, which would end up forcing both `city` and `state` to be `String`. I can look at the code with you if it's not doing that correctly.

I do think we need "whole query" inference as we don't unify type information across the whole query.

**Comment by mossprescott** [comment]
I agree these queries aren't super useful, hence the separate ticket.

Yes, we could infer the correct type for that case, but it won't help at the moment because we don't have the type annotations in the WorkflowBuilder phase.

And anyway that still leaves us with the more interesting problem where there really just isn't enough information in the query (say `foo.tags || bar.tags`)
