### ISSUE TITLE
REPL doesn't play well with shell

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#702]
It's possible to run queries by piping a file full of commands through java, like so: `java -jar core/target/scala-2.11/core_2.11-1.3.5-SNAPSHOT-one-jar.jar < test.slamsql`

However, the REPL does not really seem to handle the streams properly. It seems like the commands are being run sequentially, but not blocking each other in the right way.

1. If the input ends with `exit`, then the REPL exits immediately, before any command has a chance to produce any output.
2. If the input does *not* end with `exit`, then the REPL hangs after running all the commands, and doesn't respond to ^C or ^Z (so has to be killed from another shell).
3. All the commands are echoed (prefixed with the prompt) first, and then results are printed below. Although the results seem to be produced one at a time and in the correct order, it's hard to match them back to the commands.

**Comment by sellout** [comment]
So, I use Eshell, which means I let a lot of little oddities slip by, because it’s a somewhat odd shell. In any case, I _always_ see the command echoed before the query is run.

I briefly looked for where we might be triggering that, but I mentioned it to @mossprescott and he looked at me like I was crazy, so I figured it must be Eshell oddness. But now it sounds like maybe Eshell just interacts more like redirected I/O than like normal shell interaction?

Not that that helps. Just an observation.

Also, I’m surprised the REPL doesn’t exit when the input terminates. I feel like we shouldn’t need to include `exit` in the input (of course, it should probably still work if we do).

**Comment by mossprescott** [comment]
Right, I didn't think about that, but (2) is certainly another symptom of the REPL not handling EOF/^D correctly (see #446).
