### ISSUE TITLE
sum(1) does not work

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#835]

**Comment by mossprescott** [comment]
`sum(1)` works fine in some queries. Ex.: `select city, sum(1) from zips`, however when expressions like it are combined with other projections in certain ways, things break:

If all projections are aggregate functions of the same constant, we fail with a runtime error trying to store the value in a temp collection. Ex.: `select sum(1) from zips` -> `MongoDB cannot store anything except documents inside collections: Int64(1)`. The same applies to `avg(0)`, `min('abc')`, and so on.

If I combine an aggregate-of-constant with a legitimate aggregation, the planner fails. Ex.: `select count(*), sum(1) from zips` -> `Can not perform `objectConcat`, because unrecognized shapes` (however, adding additional projections will sometimes make that work).

And some other variations result in merge failures in the planner. Ex.: `select count(*), city, sum(1), city from zips`
