### ISSUE TITLE
mongodb: count semantics is incorrect

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#885]
When `count`'s argument is *not* `*`, the semantics according to the SQL standard is to return the number of rows for which the expression is not null. Presently, we ignore the argument and simply count the rows.

For example, with our test data, the query `SELECT count(*), count(val), count(nested.foo) FROM nullsWithMissing` should produce `5, 1, 1`, but instead you get `5, 5, 5`.

**Comment by sellout** [comment]
This is effectively true for all SQL aggregation.

We need to decide on the LP semantics of `Reduction`s containing `Null`.

1. **always ignore nulls**, which would mean our semantics match SQL, but we need to insert filtering for at least `count` in MongoDB, maybe others.
2. **return null if aggregation contains null**, which is generally our approach to null in other places, but means that the SQL compiler needs to insert a `Filter` before each `Reduction` (backends can optimize them away in certain cases), and it may be difficult/slow to replicate the non-filtered behavior in some backends.
3. any other options?

I’m inclined toward 2.

**Comment by mossprescott** [comment]
I don't think (2) works. You can't implement `count(foo), foo` with Filter/Group, because rows with `null` for foo should appear in the result, but not be counted. The only way around that would be to leave the pipeline.

(1) doesn't seem that bad. For `count`, we would need something like `$sum($cond($field("foo") == null, 0, 1)` I suspect most of the other aggregate funcs may already have the right behavior.

**Comment by sellout** [comment]
Do you mean you can’t implement it in the LP or in Mongo? Neither seems like a problem to me (but I could very well be wrong). EG, you can `$push` foo, then filter and reduce the resulting array.

**Comment by jdegoes** [comment]
In MRA there is a distinction between `null` (a sentinel value introduced by a user) and `undefined` (a "non-existing" value generated by the system). Undefineds cannot be counted because they are not values; they are placeholders representing the lack of a value. But it's perfectly valid to count nulls.

Of course, our final semantics for SQL may differ arbitrarily from MRA, but the more divergence, the more torturous the compilation. An example of divergence is a reduction applied to a constant (e.g. `COUNT(1)`), which in MRA is equivalent to reducing a singleton set (e.g. `COUNT(1) = 1`), but in SQL is a reduction over a constant column (a set whose cardinality is equal to that of the input set).

Anyway, I think that in general, we should think of every reduction as being a monoid on some structural type. The monoid won't be used for reduction on mis-matching types (for example, a hypothetical `ADD_ALL` reduction will only see numeric values). So whether or not a monoid can process `null` is a function of its structural type. So a `COUNT` function can choose whether or not to count `null` values (although it cannot count undefined values).

All of this is further complicated by the fact that we currently conflate nulls and undefineds because MongoDB doesn't have good support for undefineds (despite the fact that BSON supports an undefined value)...
